<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1.3.2 The MIX assembly language – The Little Book of The Art of Computer Programming Solutions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../vol-1/1.3.3.html" rel="next">
<link href="../vol-1/1.3.1.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-1fe81d0376b2c50856e68e651e390326.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-27c261d06b905028a18691de25d09dde.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../vol-1/1.3.2.html"><span class="chapter-title">1.3.2 The MIX assembly language</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">The Little Book of The Art of Computer Programming Solutions</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">index.html</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.1 Algorithms</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.2.1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2.1 Mathematical induction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.2.2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2.2 Numbers, powers, and logarithms</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.2.3.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2.3 Sums and products</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.2.4.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2.4 Integer functions and elementary number theory</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.2.5.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2.5 Permutations and factorials</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.2.6.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2.6 Binomial coefficients</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.2.7.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2.7 Harmonic numbers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.2.8.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2.8 Fibonacci numbers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.2.9.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2.9 Generating functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.2.10.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2.10 Analysis of an Algorithm</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.2.11.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.2.11 Asymptotic representations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.3.1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.3.1 Description of MIX</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.3.2.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">1.3.2 The MIX assembly language</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.3.3.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.3.3 Applications to Permutation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.4.1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.4.1 Subroutines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.4.2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.4.2 Coroutines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.4.3.1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.4.3.1 A MIX simulator</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.4.3.2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.4.3.2 Trace routines</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vol-1/1.4.4.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1.4.4 Input and Output</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#section" id="toc-section" class="nav-link active" data-scroll-target="#section">1 [00]</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1">2 [10]</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2">3 [23]</a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3">4 [25]</a></li>
  <li><a href="#section-4" id="toc-section-4" class="nav-link" data-scroll-target="#section-4">5 [11]</a></li>
  <li><a href="#hm20" id="toc-hm20" class="nav-link" data-scroll-target="#hm20">6 [HM20]</a></li>
  <li><a href="#section-5" id="toc-section-5" class="nav-link" data-scroll-target="#section-5">7 [10]</a></li>
  <li><a href="#section-6" id="toc-section-6" class="nav-link" data-scroll-target="#section-6">8 [24]</a></li>
  <li><a href="#section-7" id="toc-section-7" class="nav-link" data-scroll-target="#section-7">9 [25]</a></li>
  <li><a href="#section-8" id="toc-section-8" class="nav-link" data-scroll-target="#section-8">10 [31]</a></li>
  <li><a href="#m29" id="toc-m29" class="nav-link" data-scroll-target="#m29">11 [M29]</a></li>
  <li><a href="#hm42" id="toc-hm42" class="nav-link" data-scroll-target="#hm42">12 [HM42]</a></li>
  <li><a href="#section-9" id="toc-section-9" class="nav-link" data-scroll-target="#section-9">13 [28]</a></li>
  <li><a href="#section-10" id="toc-section-10" class="nav-link" data-scroll-target="#section-10">14 [31]</a></li>
  <li><a href="#m30" id="toc-m30" class="nav-link" data-scroll-target="#m30">15 [M30]</a></li>
  <li><a href="#section-11" id="toc-section-11" class="nav-link" data-scroll-target="#section-11">16 [31]</a></li>
  <li><a href="#hm30" id="toc-hm30" class="nav-link" data-scroll-target="#hm30">17 [HM30]</a></li>
  <li><a href="#section-12" id="toc-section-12" class="nav-link" data-scroll-target="#section-12">18 [25]</a></li>
  <li><a href="#m30-1" id="toc-m30-1" class="nav-link" data-scroll-target="#m30-1">19 [M30]</a></li>
  <li><a href="#section-13" id="toc-section-13" class="nav-link" data-scroll-target="#section-13">20 [33]</a></li>
  <li><a href="#section-14" id="toc-section-14" class="nav-link" data-scroll-target="#section-14">21 [28]</a></li>
  <li><a href="#section-15" id="toc-section-15" class="nav-link" data-scroll-target="#section-15">22 [31]</a></li>
  <li><a href="#section-16" id="toc-section-16" class="nav-link" data-scroll-target="#section-16">23 [37]</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">1.3.2 The MIX assembly language</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section">1 [00]</h3>
<p>Use a literal constant, load it to A, then store the whole word to X.</p>
<pre><code>        LDA   =+1000=     * A ← 1000 (literal)
        STA   X           * X ← 1000 (stores full word, field 0:5)
...
X       CON   0           * (somewhere: reserve the cell for X)</code></pre>
<p><code>X EQU 1000</code> only defines a symbol; it doesn’t write memory. <code>LDA =1000=</code> makes the value 1000 available at run time, and <code>STA X</code> sets the memory cell named <code>X</code> to 1000.</p>
</section>
<section id="section-1" class="level3">
<h3 class="anchored" data-anchor-id="section-1">2 [10]</h3>
<p>Because the word labeled <code>EXIT</code> (which contains <code>JMP *</code>) is self-modified at entry to the subroutine.</p>
<p>Line 3 does <code>STJ EXIT 1</code>. In MIX, <code>STJ …,1</code> stores the contents of <code>rJ</code> (the caller’s return address) into the address field of the memory word at <code>EXIT</code>. Thus the instruction at <code>EXIT</code> is changed from</p>
<pre><code>JMP *</code></pre>
<p>(where <code>*</code> initially means “this location”) to</p>
<pre><code>JMP &lt;return address&gt;</code></pre>
<p>When line 12 executes, it jumps to that stored return address, not to itself, so there is no infinite loop.</p>
</section>
<section id="section-2" class="level3">
<h3 class="anchored" data-anchor-id="section-2">3 [23]</h3>
<p>It’s a selection-sort wrapper around subroutine <strong>M (MAXIMUM)</strong>.</p>
<ol type="1">
<li><p><code>IN X+1(0)</code> / <code>JBUS *(0)</code> reads 100 words into <code>X[1]..X[100]</code> and waits.</p></li>
<li><p><code>ENT1 100</code> sets <code>n ← 100</code>.</p></li>
<li><p>Loop (<code>1H … J1P 1B</code>):</p>
<ul>
<li><code>JMP MAXIMUM</code> calls Program M, which returns the maximum of <code>X[1..n]</code> in <code>A</code> and its index in <code>rI2 = j</code>.</li>
<li><code>LDX X,1</code> loads <code>X[n]</code> into <code>X</code>.</li>
<li><code>STA X,1</code> stores the max at <code>X[n]</code>.</li>
<li><code>STX X,2</code> stores the old <code>X[n]</code> at <code>X[j]</code> (swap).</li>
<li><code>DEC1 1</code> decrements <code>n</code>; repeat while <code>n &gt; 0</code>.</li>
</ul></li>
<li><p><code>OUT X+1(1)</code> outputs the block; <code>HLT</code> stops.</p></li>
</ol>
<p>Effect: it sorts the 100 input numbers in nondecreasing (ascending) order, placing the largest remaining element at the end on each pass, then prints the sorted list.</p>
</section>
<section id="section-3" class="level3">
<h3 class="anchored" data-anchor-id="section-3">4 [25]</h3>
<p>Here’s a clean hand-assembly of <strong>Program P</strong>. I’m using the MIX instruction format (ADDRESS, INDEX, MOD, OPCODE); <code>MOD</code> is either the field spec (for LD/ST/CMP/ADD/SUB/…; default (0:5) =&gt; 5) or the operation modifier (for ENTx/INCx/DECx, Jx, I/O, etc.). MIX opcodes and field rules come straight from the standard tables.</p>
<p><strong>Symbols resolved</strong></p>
<ul>
<li><code>L = 500</code>, <code>PRINTER = 18</code>, <code>PRIME = -1</code>, <code>BUF0 = 2000</code>, <code>BUF1 = BUF0+25 = 2025</code>.</li>
<li>Local labels: <code>2H</code> at 3003 and 3016 and 3019; <code>4H</code> at 3006 and 3020; <code>6H</code> at 3008.</li>
<li>Literal pool (placed <em>after</em> the program end): <code>=1-L= → -499</code>, <code>=3= → 3</code>.</li>
</ul>
<p><strong>Code (ORIG 3000)</strong></p>
<p>Each line shows: <code>LOC : + ADDRESS  INDEX  MOD  OPCODE   ; mnemonic / remark</code>.</p>
<pre><code>3000: +    0  0 18 35   ; IOC 0(PRINTER)
3001: + 2050  0  5  9   ; LD1 =1-L=         (literal at 2050)
3002: + 2051  0  5 10   ; LD2 =3=           (literal at 2051)
3003: +    1  0  0 49   ; INC1 1            (2H)
3004: +  499  1  5 26   ; ST2 PRIME+L,1
3005: + 3016  0  1 41   ; J1Z 2F
3006: +    2  0  0 50   ; INC2 2            (4H)
3007: +    2  0  2 51   ; ENT3 2
3008: +    0  0  2 48   ; ENTA 0            (6H)
3009: +    0  2  2 55   ; ENTX 0,2
3010: +   -1  3  5  4   ; DIV PRIME,3
3011: + 3006  0  1 47   ; JXZ 4B
3012: +   -1  3  5 56   ; CMPA PRIME,3
3013: +    1  0  0 51   ; INC3 1
3014: + 3008  0  6 39   ; JG 6B
3015: + 3003  0  0 39   ; JMP 2B
3016: + 1995  0 18 37   ; OUT TITLE(PRINTER)      (2H)
3017: + 2035  0  2 52   ; ENT4 BUF1+10
3018: +  -50  0  2 53   ; ENT5 -50
3019: +  501  0  0 53   ; INC5 L+1                (2H)
3020: +   -1  5  5  8   ; LDA PRIME,5             (4H)
3021: +    0  0  1  5   ; CHAR
3022: +    0  4 12 31   ; STX 0,4(1:4)  (MOD=8*1+4=12)
3023: +    1  0  1 52   ; DEC4 1
3024: +   50  0  1 53   ; DEC5 50
3025: + 3020  0  2 45   ; J5P 4B
3026: +    0  4 18 37   ; OUT 0,4(PRINTER)
3027: +   24  4  5 12   ; LD4 24,4
3028: + 3019  0  0 45   ; J5N 2B
3029: +    0  0  2  5   ; HLT</code></pre>
<p>Why those numbers?</p>
<ul>
<li>LD/STA/… opcodes and default field <code>5</code> (i.e., (0:5)) per MIX tables.</li>
<li>ENTx/INCx/DECx share opcodes 48–55; <code>MOD</code> distinguishes ENT (2), INC (0), DEC (1).</li>
<li>Jumps: <code>J1Z</code> uses opcode 40+i (=41) with <code>MOD=1</code>; <code>JXZ</code> uses opcode 47 with <code>MOD=1</code>; <code>JG</code>/<code>JMP</code> use opcode 39 with <code>MOD=6</code>/<code>0</code>.</li>
<li>I/O: <code>IOC</code>/<code>OUT</code> are opcodes 35/37 with <code>MOD=unit#</code> (18 = line printer).</li>
<li><code>CHAR</code> is opcode 5 with <code>MOD=1</code>; <code>HLT</code> is opcode 5 with <code>MOD=2</code>.</li>
</ul>
<p><strong>Data and text words</strong></p>
<p>MIX stores numbers base-64 per byte; below I show each word as five byte values (sign shown first). Example: 2000 = <code>+ 00 00 00 31 16</code>.</p>
<p>Primes table head (ORIG PRIME+1 = 0):</p>
<pre><code>0000: + 00 00 00 00 02   ; CON 2  (PRIME[1])</code></pre>
<p>Title (ORIG BUF0–5 = 1995) — ALF encodes characters to MIX byte codes (A=1…Z=29, space=0, digits 0–9→30–39, etc.).</p>
<pre><code>1995: + 06 09 19 22 23   ; ALF 'FIRST'
1996: + 00 06 09 25 05   ; ALF ' FIVE'
1997: + 00 08 24 15 04   ; ALF ' HUND'
1998: + 19 05 04 00 17   ; ALF 'RED P'
1999: + 19 09 14 05 22   ; ALF 'RIMES'</code></pre>
<p>Buffer cross-pointers:</p>
<pre><code>2024: + 00 00 00 31 51   ; CON BUF1+10 (=2035)
2049: + 00 00 00 31 26   ; CON BUF0+10 (=2010)</code></pre>
<p>Literal pool (placed after END):</p>
<pre><code>2050: - 00 00 00 07 51   ; =1-L=  (−499)
2051: + 00 00 00 00 03   ; =3=    (+3)</code></pre>
<pre class="text"><code>* Program P — fully assembled numeric image (matches Knuth’s listing).
* Symbols:  L=500, PRINTER=18, PRIME=-1, BUF0=2000, BUF1=BUF0+25=2025
* Local labels: 2H at 3003, 3016, 3019; 4H at 3006, 3020; 6H at 3008
* Word layout shown as:  sign  ADDRESS  INDEX  MOD  OPCODE
* Notes:
*  - For I/O, MOD = device number. Line printer is 18.
*  - For LD/ST/CMP/arith, MOD = field spec; default (0:5) is encoded as 5.
*  - ENT/INC/DEC families use MOD=2/0/1 respectively; register selects opcode.
*  - Jumps on Ix use opcodes 40..47 (rI1..rX); MOD encodes the condition.
*  - JG/JMP use opcode 39 with MOD=6/0. CHAR and HLT are opcode 5 with MOD=1/2.

3000: + 0000 00 18 35   ; IOC 0(PRINTER) — device 18 → MOD=18, opcode 35
3001: + 2051 00 05 09   ; LD1 =1-L=     — literal at 2051 (=1−500=-499), field (0:5)
3002: + 2050 00 05 10   ; LD2 =3=       — literal at 2050 (+3), field (0:5)
3003: + 0001 00 00 49   ; INC1 1        — MOD=0 for INC, opcode for rI1 is 49      (2H)
3004: + 0499 01 05 26   ; ST2 PRIME+L,1 — addr = -1+500 = +499, indexed by rI1, store rI2
3005: + 3016 00 01 41   ; J1Z 2F        — jump if rI1==0 to forward “2H” at 3016
3006: + 0002 00 00 50   ; INC2 2        — rI2 ← rI2+2                                 (4H)
3007: + 0002 00 02 51   ; ENT3 2        — rI3 ← +2 (ENT uses MOD=2)
3008: + 0000 00 02 48   ; ENTA 0        — rA  ← 0                                     (6H)
3009: + 0000 02 02 55   ; ENTX 0,2      — rX  ← rI2 (index 2 named after comma-2)
3010: - 0001 03 05 04   ; DIV PRIME,3   — divide A‖X by mem[-1+X3], fld (0:5)
3011: + 3006 00 01 47   ; JXZ 4B        — if rX==0 goto back “4H” at 3006
3012: - 0001 03 05 56   ; CMPA PRIME,3  — compare A with mem[-1+X3], fld (0:5)
3013: + 0001 00 00 51   ; INC3 1        — rI3 ← rI3+1
3014: + 3008 00 06 39   ; JG 6B         — if A&gt;0 goto back “6H” at 3008 (MOD=6)
3015: + 3003 00 00 39   ; JMP 2B        — unconditional to back “2H” at 3003
3016: + 1995 00 18 37   ; OUT TITLE(PRINTER) — addr of TITLE=1995, device 18     (2H)
3017: + 2035 00 02 52   ; ENT4 BUF1+10  — rI4 ← 2025+10=2035
3018: - 0050 00 02 53   ; ENT5 -50      — rI5 ← -50
3019: + 0501 00 00 53   ; INC5 L+1      — rI5 ← rI5 + 501 (L+1=501)                 (2H)
3020: - 0001 05 05 08   ; LDA PRIME,5   — A ← mem[-1] (full word)                    (4H)
3021: + 0000 00 01 05   ; CHAR          — convert A to 10 chars packed into A‖X
3022: + 0000 04 12 31   ; STX 0,4(1:4)  — store X’s middle bytes; (1:4)→MOD=8*1+4=12; idx rI4
3023: + 0001 00 01 52   ; DEC4 1        — rI4 ← rI4−1  (MOD=1 for DEC)
3024: + 0050 00 01 53   ; DEC5 50       — rI5 ← rI5−50; will loop while still &gt;0
3025: + 3020 00 02 45   ; J5P 4B        — if rI5&gt;0 goto back “4H” at 3020
3026: + 0000 04 18 37   ; OUT 0,4(PRINTER) — print buffer whose addr is in rI4 (index 4), device 18
3027: + 0024 04 05 12   ; LD4 24,4      — rI4 ← mem[24+X4] (switch buffer pointer)
3028: + 3019 00 00 45   ; J5N 2B        — if rI5&lt;0 goto back “2H” at 3019 (done when ≤0)
3029: + 0000 00 02 05   ; HLT           — stop (opcode 5, MOD=2)

* ----- Data and text areas ----------------------------------------------------

0000: +                                2  ; PRIME[1] = 2   (ORIG PRIME+1 / CON 2)

1995: + 06 09 19 22 23                     ; ALF 'FIRST'
1996: + 00 06 09 25 05                     ; ALF ' FIVE'  (note leading blank)
1997: + 00 08 24 15 04                     ; ALF ' HUND'
1998: + 19 05 04 00 17                     ; ALF 'RED P'
1999: + 19 09 14 05 22                     ; ALF 'RIMES'

2024: +                               2035 ; BUF0+24 → BUF1+10 (cross-pointer)
2049: +                               2010 ; BUF1+24 → BUF0+10 (cross-pointer)

* ----- Literal pool placed after the program ---------------------------------
2050: +                                  3 ; =3=          (used by LD2 at 3002)
2051: -                                499 ; =1-L= = 1−500 (used by LD1 at 3001)

* Sanity checks you can do when re-deriving:
*  - All forward/backward locals resolve to the stated addresses:
*      2F=3016, 4B=3006/3020, 6B=3008, 2B=3019/3003 as indicated.
*  - Field (1:4) encodes as MOD=8*1+4=12 (see 3022).
*  - I/O MODs are 18 throughout; jump MODs: Z=1, P=2, N=0; JG uses MOD=6.</code></pre>
</section>
<section id="section-4" class="level3">
<h3 class="anchored" data-anchor-id="section-4">5 [11]</h3>
<p>Because Program P does a <em>lot</em> of work between two output operations and it double-buffers the line being printed.</p>
<p><code>OUT 0,4(PRINTER)</code> starts the printer asynchronously and the program immediately switches <code>rI4</code> to the other buffer (<code>LD4 24,4</code>). It then spends a long time computing the next 50 primes and formatting them into that other buffer. By the time it reaches the next <code>OUT</code>, the printer has finished the previous line and is ready again. Since the program never touches the buffer that’s currently being printed (thanks to the alternating buffers), it doesn’t need to poll the device with <code>JBUS</code>.</p>
</section>
<section id="hm20" class="level3">
<h3 class="anchored" data-anchor-id="hm20">6 [HM20]</h3>
<ol type="a">
<li><p>If <span class="math inline">\(n\)</span> is composite, write <span class="math inline">\(n=ab\)</span> with <span class="math inline">\(1&lt;a\le b&lt;n\)</span>. If both <span class="math inline">\(a&gt;\sqrt n\)</span> and <span class="math inline">\(b&gt;\sqrt n\)</span>, then <span class="math inline">\(ab&gt;\sqrt n\cdot\sqrt n=n\)</span>, a contradiction. Hence at least one factor is <span class="math inline">\(\le\sqrt n\)</span>. Let <span class="math inline">\(d=\min(a,b)\)</span>; then <span class="math inline">\(1&lt;d\le\sqrt n\)</span>.</p></li>
<li><p>In Program <strong>P</strong>, step <strong>P6</strong> divides <span class="math inline">\(N\)</span> by the current prime <span class="math inline">\(p=\text{PRIME}[k]\)</span>: <span class="math inline">\(N = pQ + R\)</span> with <span class="math inline">\(0\le R&lt;p\)</span>. MIX puts <span class="math inline">\(Q\)</span> in <span class="math inline">\(rA\)</span> and <span class="math inline">\(R\)</span> in <span class="math inline">\(rX\)</span>. If <span class="math inline">\(R=0\)</span> the program declares “not prime”.</p></li>
</ol>
<p>Step <strong>P7</strong> (the code <code>CMPA PRIME,3; INC3 1; JG 6B</code>) compares that quotient <span class="math inline">\(Q\)</span> with the <strong>next</strong> prime <span class="math inline">\(p'=\text{PRIME}[k+1]\)</span> and loops back to <strong>P6</strong> exactly when <span class="math inline">\(p' \le Q\)</span>.</p>
<p>Why does stopping when <span class="math inline">\(p' &gt; Q\)</span> prove primality? If <span class="math inline">\(p\le\sqrt N\)</span> then <span class="math inline">\(\displaystyle Q=\left\lfloor \frac{N}{p}\right\rfloor \ge \sqrt N\)</span>. Therefore any prime divisor <span class="math inline">\(\le\sqrt N\)</span> is <span class="math inline">\(\le Q\)</span>. Program <strong>P</strong> tries primes in increasing order; as long as there could still be a prime <span class="math inline">\(\le\sqrt N\)</span> left, we have <span class="math inline">\(p' \le Q\)</span> and the loop continues. When the test first finds <span class="math inline">\(p' &gt; Q\)</span>, every remaining prime exceeds <span class="math inline">\(Q \ge \sqrt N\)</span>. Since we have already checked all smaller primes (and none divided <span class="math inline">\(N\)</span>), <span class="math inline">\(N\)</span> has no divisor <span class="math inline">\(\le\sqrt N\)</span>. By part (a), <span class="math inline">\(N\)</span> must be prime.</p>
</section>
<section id="section-5" class="level3">
<h3 class="anchored" data-anchor-id="section-5">7 [10]</h3>
<ol type="a">
<li><p>In MIXAL a digit with “B” means “the nearest <strong>previous</strong> line whose location is that digit followed by H.” So the <code>4B</code> in line 34 means “jump to the most recent <code>4H</code> before this line,” which here is line 29 (address 3020). Thus <code>J5P 4B</code> jumps back to 3020 when rI5 &gt; 0.</p></li>
<li><p>If we relabel line 15 as <code>2H</code> and change the target of line 20 to <code>2B</code>:</p></li>
</ol>
<ul>
<li>Line 20 will still jump to line 15 (because <code>2B</code> now refers to the nearest previous <code>2H</code>, which would be the newly labeled line 15). So that branch is unchanged.</li>
<li>But line 24 already contains <code>JMP 2B</code>. After the relabel, its target changes from the old <code>2H</code> at line 12 (step P2: store the prime and increment <span class="math inline">\(J\)</span>) to the new <code>2H</code> at line 15 (step P4: advance <span class="math inline">\(N\)</span>). That means whenever <span class="math inline">\(N\)</span> is prime the program would skip storing it and skip incrementing <span class="math inline">\(J\)</span>. Consequently <span class="math inline">\(J\)</span> never reaches 500, so the “500 found?” test never triggers and the printing phase never runs—effectively breaking the program (it will keep searching forever).</li>
</ul>
<p>So: (a) “previous 4H” (line 29). (b) The change is not harmless; it makes line 24 jump to the wrong place and the program fails to record primes or terminate.</p>
</section>
<section id="section-6" class="level3">
<h3 class="anchored" data-anchor-id="section-6">8 [24]</h3>
<p>Here’s the original “mystery program” rewritten with <strong>inline MIXAL comments</strong> so you can see exactly what every line does:</p>
<pre><code>* MYSTERY PROGRAM (annotated)

BUF   ORIG **+3000          * Define BUF as an address 3000 words ahead of here.
                            * Code that follows runs before BUF; BUF.. is our data area.

1H    ENT1 1                * I1 ← 1           (run-length to write)
      ENT2 0                * I2 ← 0           (write pointer into BUF)
      LDX  4F               * X  ← word at 4H  (ALF AAAAA) → X="AAAAA"

2H    ENT3 0,1              * I3 ← 0+I1        (copy I1 into I3: loop counter)

3H    STZ  BUF,2            * BUF[I2] ← +0     (store a blank word)
      INC2 1                * I2++             (advance pointer)
      DEC3 1                * I3--             (one blank done)
      J3P  3B               * if I3&gt;0, repeat from 3H (write exactly I1 blanks)

      STX  BUF,2            * BUF[I2] ← X      ('AAAAA' after the blanks)
      INC2 1                * I2++             (advance after the 'A' word)
      INC1 1                * I1++             (next time, one more blank)
      CMP1 =75=             * compare I1 with 75
      JL   2B               * if I1&lt;75, go back to 2H and build next block

      ENN2 2400             * I2 ← −2400       (set up to print from BUF upward)
      OUT  BUF+2400,2(18)   * print one line (24 words) starting at BUF+2400+I2;
                            * device 18 = line printer. With I2&lt;0 this starts at BUF.
      INC2 24               * I2 += 24         (next line starts 24 words later)
      J2N  *-2              * while I2&lt;0, jump back two lines to OUT (prints 100 lines)
      HLT                   * done

4H    ALF  AAAAA            * AAAAA literal used above (loaded into X)
      END  1B               * entry is at label 1H</code></pre>
<p><strong>What it does</strong></p>
<p>Phase 1 (building the buffer). Starting at <code>BUF</code>, the program writes a pattern: for <code>k = 1, 2, …, 74</code>, it stores <strong>k blank words</strong> (each is <code>+0</code>, which prints as five spaces) followed by the word <strong><code>AAAAA</code></strong>. After the last iteration (<code>k=74</code>) it stops. The total words written are <span class="math inline">\(\sum_{k=1}^{74}(k+1) = 2849\)</span>. The positions of the <code>AAAAA</code> words within the buffer are</p>
<p><span class="math display">\[
p_m=\sum_{k=1}^{m}(k+1)=\frac{m(m+3)}{2}\quad(m=1,2,\dots,74)
\]</span></p>
<p>i.e., at word numbers <span class="math inline">\(2,5,9,14,20,27,\dots\)</span> with gaps growing by <span class="math inline">\(3,4,5,\ldots\)</span>.</p>
<p>Phase 2 (printing). It then prints the <strong>first 2400 words</strong> of this buffer as <strong>100 lines</strong> of the line printer (24 words = 120 characters per line), starting at <code>BUF</code>, then <code>BUF+24</code>, <code>BUF+48</code>, …, <code>BUF+2376</code>. Because blank words render as spaces and the nonblank words render as <code>AAAAA</code>, the page shows a sequence of <code>AAAAA</code> blocks separated by ever-increasing runs of spaces—a triangular/“quadratically spaced” pattern of A’s drifting across the printed lines.</p>
</section>
<section id="section-7" class="level3">
<h3 class="anchored" data-anchor-id="section-7">9 [25]</h3>
<p>Here’s a clean, table-driven MIXAL solution that validates a word in <code>INST</code>. It jumps to <code>GOOD</code> iff the instruction has a valid C-field (opcode), ±AA field (address) when required, I-field (index), and F-field; otherwise it jumps to <code>BAD</code>.</p>
<pre class="mixal"><code>* EX 1.3.2–9 — Verify that INST is a legal MIX instruction.
* If legal, jump to GOOD; otherwise jump to BAD.

            ORIG 3000

* ---------- Small constants and helpers --------------------------------------

B       EQU  1(4:4)          * MIX byte size (b = 64) via the canonical trick
BMAX    EQU  B-1             * for MOVE: F ∈ [0..b-1]
UMAX    EQU  20              * highest I/O unit number in the MIX spec

* VALID packs several convenient bounds into one word:
* (3:3)=6  → upper bound for I
* address=3999 → largest legal memory address
* (4:4)=6  → “floating” F used by arithmetic ops (ADD/SUB/MUL/DIV)
VALID   CMPX 3999,6(6)

INST    CON  0               * (caller puts candidate instruction here)

* ---------- Common front-end checks + table dispatch --------------------------

BEGIN   LDA   INST                   * A ← INST (full word)
        CMPA  VALID(3:3)             * compare I with 6
        JG    BAD                    * I &gt; 6 → illegal

        LD1   INST(5:5)              * I1 ← opcode (C)
        DEC1  64
        J1NN  BAD                    * C ≥ 64 → illegal (not an instruction)

        CMPA  TABLE+64,1(4:4)        * compare F with per-opcode Fmax from table
        JG    BAD                    * F &gt; Fmax → illegal

        LD1   TABLE+64,1(1:2)        * I1 ← address of per-opcode checker
        JMP   0,1                    * jump there

* ---------- Per-opcode checker routines --------------------------------------

* FLOAT — arithmetic ops: either a valid partial field or F==6 (“floating”)
FLOAT   CMPA  VALID(4:4)             * F == 6 ?
        JE    MEMORY                 * if yes, only the address rule remains
        JMP   FIELD                  * else check partial field as usual

* FIELD — validate F as 8L+R with 0 ≤ L ≤ R ≤ 5
* Trick: let F = 8L+R, divide by 9 →  A = ⌊F/9⌋ and X = F mod 9.
* - If R ≥ L:  ⌊F/9⌋=L, rem=R-L → A+rem = R → require R ≤ 5.
* - If R &lt; L:  ⌊F/9⌋=L−1, rem=R−L+9 → A+rem = R+8 ≥ 8 → reject.
FIELD   ENTA  0
        LDX   INST(4:4)              * X ← F
        DIV   =9=
        STX   *+1(0:2)               * self-modify the next INCA with rem
        INCA  0                      * A ← ⌊F/9⌋ + (F mod 9)
        DECA  5
        JAP   BAD                    * if &gt;5 → illegal
        JMP   MEMORY                 * finally validate the address if needed

* MEMORY — when I=0, address must be a valid memory/unit number
MEMORY  LDX   INST(3:3)              * X ← I
        JXNZ  GOOD                   * if I ≠ 0, indexing OK → done
        LDX   INST(0:2)              * X ← ±AA (or device/unit for I/O)
        JXN   BAD                    * negative address/unit not allowed
        DECX  3999
        JXNP  GOOD                   * 0..3999 is OK (table narrows bound for I/O)
        JMP   BAD

GOOD    JMP   GOOD                   * (return address patched by caller)
BAD     JMP   BAD

* ---------- Opcode table: Fmax in (4:4), checker address in (1:2) -------------
* The pattern is what matters; you can fill remaining opcodes analogously.
* N.B.: For opcodes that do not use ±AA, the checker is just GOOD.
*       For I/O and MOVE, the checker is MEMORY with the appropriate bound.

TABLE   NOP    GOOD(BMAX)            * C=0  : any F up to B−1 is harmless
        ADD    FLOAT(5:5)            * C=1  : arithmetic allow F=6 (‘floating’)
        SUB    FLOAT(5:5)            * C=2
        MUL    FLOAT(5:5)            * C=3
        DIV    FLOAT(5:5)            * C=4
        HLT    GOOD                  * C=5  : F ignored; no address use
        SRC    GOOD                  * C=6  : shifts/rotates; address is count
        MOVE   MEMORY(BMAX)          * C=7  : any F in [0..B−1]; addr must be valid
        LDA    FIELD(5:5)            * C=8  : partial fields only
* ...   (fill remaining opcodes in the same style:
*        all loads/stores &amp; compares → FIELD(5:5);
*        address-using ops (e.g., Jxx, I/O) → MEMORY with proper bound;
*        ops with no address effect (e.g., NOP/HLT/SRC) → GOOD.)
* -----------------------------------------------------------------------------

        END   BEGIN</code></pre>
<p><strong>How it works</strong></p>
<ol type="1">
<li><p><strong>Front-end</strong> rejects illegal <code>I</code> (must be ≤6) and <code>C</code> (must be &lt;64), then checks <code>F ≤ Fmax(C)</code> from the table.</p></li>
<li><p><strong>Dispatch</strong> jumps to an <strong>opcode-specific checker</strong> from the same table entry:</p>
<ul>
<li><code>FLOAT</code> accepts the special case <code>F=6</code> for arithmetic; otherwise it falls through to <code>FIELD</code>.</li>
<li><code>FIELD</code> verifies a partial field by dividing <code>F</code> by 9 (the classic MIX trick), accepting iff <code>0 ≤ L ≤ R ≤ 5</code>.</li>
<li><code>MEMORY</code> ensures that when <code>I=0</code> the address (or I/O unit) is a valid nonnegative value within bounds (3999 for memory, or a tighter bound for I/O/MOVE supplied via the table).</li>
</ul></li>
<li><p>If all checks pass, control reaches <strong>GOOD</strong>; otherwise it reaches <strong>BAD</strong>.</p></li>
</ol>
<p>This is exactly the “table + dispatch” approach Knuth recommends: it’s short, fast, and easy to extend—just adjust the two numbers in each table entry if an opcode’s rules change.</p>
</section>
<section id="section-8" class="level3">
<h3 class="anchored" data-anchor-id="section-8">10 [31]</h3>
<p>Here’s a compact, fully annotated MIXAL solution for the <strong>9×8 saddle point</strong> problem. Matrix element <span class="math inline">\(a_{ij}\)</span> lives at address <span class="math inline">\(1000+8i+j\)</span> for <span class="math inline">\(1\le i\le 9,\;1\le j\le 8\)</span>. The program scans each row, picks the <strong>row minimum</strong> <span class="math inline">\(a_{i j^{*}}\)</span>, then checks whether it is also the <strong>column maximum</strong> in column <span class="math inline">\(j^{*}\)</span>. If a saddle point is found, it leaves its <strong>address</strong> in <code>rI1</code> and halts; otherwise it halts with <code>rI1 ← 0</code>.</p>
<pre class="mixal"><code>* TAOCP v1 §1.3.2 — Ex.10  Saddle point in 9x8 matrix
* a(i,j) is stored at ADDR = 1000 + 8*i + j  (1-based i,j)

        ORIG 3000

ROWS    EQU  9
COLS    EQU  8
ROW1    EQU  1009          * addr of a(1,1)  = 1000 + 8*1 + 1
COLBAS  EQU  1008          * addr of a(1,0)  so COLBAS + j = addr of a(1,j)

* Scratch
MINVAL  CON  0             * current row minimum value
MINJ    CON  0             * column index j* (1..8) of that minimum
RSTART  CON  0             * address of a(i,1) for current row
TMP     CON  0             * temp cell for building rI1 result

* rI1: result (address or 0)
* rI3: remaining rows counter
* rI4: inner loop counter
* rI5: row pointer (address of current element in row)
* rI6: column pointer for column check

START   ENT1 0             * rI1 ← 0 by default (means "no saddle")
        ENT3 ROWS          * rI3 ← 9 rows to process
        ENT5 ROW1          * rI5 ← address of a(1,1)

RLOOP   ST5  RSTART        * remember row start address a(i,1)
        ENT2 1             * rI2 ← j = 1
        LDA  0,5           * A ← a(i,1)
        STA  MINVAL        * row minimum so far
        ST2  MINJ          * j* ← 1
        ENT4 COLS-1        * rI4 ← 7 more elements to scan in this row

* ---- scan the rest of the row, keep the minimum and its column j* ----
RNEXT   INC5 1             * move to a(i,j+1)
        INC2 1             * j ← j+1
        LDA  0,5           * A ← a(i,j)
        CMPA MINVAL
        JGE  RKEEP         * if a(i,j) &gt;= current min, keep old min
        STA  MINVAL        * else new minimum found
        ST2  MINJ
RKEEP   DEC4 1
        J4P  RNEXT

* ---- check whether the row-minimum is also a column-maximum ----
        LD6  MINJ          * rI6 ← j*
        INC6 COLBAS        * rI6 ← 1008 + j*  (points at a(1,j*))
        ENT4 ROWS          * rI4 ← 9 rows to test

CCHECK  LDA  0,6           * A ← a(k,j*)
        CMPA MINVAL
        JG   NOTSAD        * some a(k,j*) &gt; MINVAL ⇒ not a saddle
        INC6 8             * next row: address +8
        DEC4 1
        J4P  CCHECK

* Success: build the exact address 1000+8*i+j* = RSTART + (j*−1), put in rI1
        LDA  RSTART
        ADD  MINJ
        SUB  =1=
        STA  TMP
        LD1  TMP           * rI1 ← candidate address
        HLT                * done (saddle point found)

* ---- move to next row and continue the search ----
NOTSAD  LD5  RSTART        * restore this row's start address
        INC5 8             * advance to next row's a(i+1,1)
        DEC3 1
        J3P  RLOOP

        ENT1 0             * no saddle point anywhere
        HLT

        END  START</code></pre>
<p>Why it works. For each row <span class="math inline">\(i\)</span> the first loop walks from <code>a(i,1)</code> to <code>a(i,8)</code> keeping the smallest value and its column <span class="math inline">\(j^{*}\)</span>. The second loop fixes the column <span class="math inline">\(j^{*}\)</span> (pointer <code>rI6 = 1008 + j^{*}</code>) and marches down by 8 through all nine rows; if any entry exceeds the row minimum, the candidate cannot be a saddle point. Passing that test means</p>
<p><span class="math display">\[
a_{i j^{*}} \le a_{i k}\;\forall k\quad\text{and}\quad
a_{i j^{*}} \ge a_{k j^{*}}\;\forall k,
\]</span></p>
<p>so <span class="math inline">\(a_{i j^{*}}\)</span> is a saddle point and we return its <strong>memory address</strong> in <code>rI1</code>. If none is found after all 9 rows, <code>rI1</code> remains 0.</p>
</section>
<section id="m29" class="level3">
<h3 class="anchored" data-anchor-id="m29">11 [M29]</h3>
<p>Here <span class="math inline">\(m=9\)</span> rows and <span class="math inline">\(n=8\)</span> columns.</p>
<ol type="a">
<li>All 72 entries are distinct (all <span class="math inline">\(72!\)</span> orders equally likely)</li>
</ol>
<p>For a fixed cell <span class="math inline">\((i,j)\)</span> look only at the <span class="math inline">\(m+n-1\)</span> entries in its row or column: <span class="math inline">\(\{a_{i1},\dots,a_{in}\}\cup\{a_{1j},\dots,a_{mj}\}\)</span> (with <span class="math inline">\(a_{ij}\)</span> counted once).</p>
<p>To be a saddle, <span class="math inline">\(a_{ij}\)</span> must be <strong>smaller</strong> than the other <span class="math inline">\(n-1\)</span> in its row and <strong>larger</strong> than the other <span class="math inline">\(m-1\)</span> in its column. In the total order of these <span class="math inline">\(m+n-1\)</span> items this means exactly:</p>
<ul>
<li>the <span class="math inline">\(m-1\)</span> smallest are the other column-<span class="math inline">\(j\)</span> entries (in any order),</li>
<li>then comes <span class="math inline">\(a_{ij}\)</span>,</li>
<li>then the <span class="math inline">\(n-1\)</span> remaining row-<span class="math inline">\(i\)</span> entries (in any order).</li>
</ul>
<p>The number of favorable orders is <span class="math inline">\((m-1)!(n-1)!\)</span>; all <span class="math inline">\((m+n-1)!\)</span> orders are equally likely. Hence</p>
<p><span class="math display">\[
\Pr\{(i,j)\text{ is a saddle}\}=\frac{(m-1)!(n-1)!}{(m+n-1)!}.
\]</span></p>
<p>With all entries distinct there can be <strong>at most one</strong> saddle point (two would force a strict inequality cycle), so the probability the matrix has a saddle is just <span class="math inline">\(mn\)</span> times the above:</p>
<p><span class="math display">\[
\boxed{\Pr\{\text{saddle exists}\}
= \frac{mn\,(m-1)!(n-1)!}{(m+n-1)!}}.
\]</span></p>
<p>For <span class="math inline">\(m=9,\;n=8\)</span>,</p>
<p><span class="math display">\[
\Pr = \frac{72\cdot 8!\cdot 7!}{16!}
= \frac{1}{1430}
\approx 6.993\times 10^{-4}.
\]</span></p>
<ol start="2" type="a">
<li>Entries are i.i.d. 0/1 with all <span class="math inline">\(2^{72}\)</span> matrices equally likely</li>
</ol>
<p>A cell is a saddle iff either • it is a <strong>0</strong> and its <strong>column is all zeros</strong>, or • it is a <strong>1</strong> and its <strong>row is all ones</strong>.</p>
<p>Thus a saddle exists iff there is <strong>at least one all-zero column</strong> or <strong>at least one all-one row</strong>. These two events are disjoint (they cannot happen together because their intersection cell would have to be both 0 and 1).</p>
<p>Columns are independent, so</p>
<p><span class="math display">\[
\Pr\{\text{some column all 0}\}
=1-\bigl(1-2^{-9}\bigr)^8.
\]</span></p>
<p>Rows are independent, so</p>
<p><span class="math display">\[
\Pr\{\text{some row all 1}\}
=1-\bigl(1-2^{-8}\bigr)^9.
\]</span></p>
<p>Therefore</p>
<p><span class="math display">\[
\boxed{\Pr\{\text{saddle exists}\}
= \bigl[1-(1-2^{-9})^{8}\bigr]
+ \bigl[1-(1-2^{-8})^{9}\bigr]}
= \frac{924744796234036231}{2^{64}}
\approx 0.0501305159.
\]</span></p>
<p>So: about <span class="math inline">\(0.0699\%\)</span> in the distinct-entries case, and about <span class="math inline">\(5.01\%\)</span> in the 0/1 case.</p>
</section>
<section id="hm42" class="level3">
<h3 class="anchored" data-anchor-id="hm42">12 [HM42]</h3>
<p><strong>The algorithms</strong></p>
<ul>
<li><strong>Sol. 1 (row-min then check its column):</strong> For each row, scan the 8 entries to get the row minimum (and all columns where it occurs), then for each such column scan downward until you see a larger value; if none, you’ve found a saddle.</li>
<li><strong>Sol. 2 (min of column-maxima):</strong> Phase 1: compute every column maximum <span class="math inline">\(C(j)\)</span> and then <span class="math inline">\(c_{\min}=\min_j C(j)\)</span>. Phase 2: run across each row; if you ever see an entry <span class="math inline">\(&lt;c_{\min}\)</span> the row can’t contain a saddle; otherwise look for an entry <span class="math inline">\(=c_{\min}\)</span> (then you have a saddle).</li>
<li><strong>Sol. 3 (suggested):</strong> Same as Sol. 2, but in Phase 1 also remember the row(s) where the minimal column-maximum occurs; search <strong>only</strong> those row(s) in Phase 2 (usually one row when there are no ties).</li>
</ul>
<p><strong>Model A: all 72 entries distinct (all orders equally likely)</strong></p>
<p>Some useful facts for i.i.d. continuous data:</p>
<ul>
<li>A row minimum among 8 is typically at the <span class="math inline">\(\approx 1/9\)</span> quantile. When you check its column you meet a larger entry with probability <span class="math inline">\(\approx 1-1/9=8/9\)</span> at each step, so the expected number of comparisons in that column is <span class="math inline">\(\approx 1/(8/9)=1.125\)</span>.</li>
<li>To form each column maximum needs 8 comparisons; finding the minimum of the 8 maxima needs 7 more. The min of the 8 column-maxima has mean <span class="math inline">\(\mathbb{E}[c_{\min}] \approx 0.7455\)</span> (for uniform[0,1]). Thus, while scanning a row in Phase 2 of Sol. 2, you hit an entry <span class="math inline">\(&lt;c_{\min}\)</span> after about <span class="math inline">\(1/\mathbb{E}[c_{\min}]\approx 1.34\)</span> comparisons on average.</li>
</ul>
<p>Rough comparison in <strong>comparisons</strong>:</p>
<ul>
<li><strong>Sol. 1:</strong> <span class="math inline">\(9\)</span> rows × (row-min <span class="math inline">\(=7\)</span> comps + column-check <span class="math inline">\(\approx 1.125\)</span>) <span class="math inline">\(\Rightarrow \; 9\times(7+1.125)\approx \mathbf{73}\)</span>.</li>
<li><strong>Sol. 2:</strong> Phase 1 <span class="math inline">\(=8\cdot 8+7= \mathbf{71}\)</span>; Phase 2 <span class="math inline">\(=9\times 1.34\approx 12\)</span>. Total <span class="math inline">\(\approx \mathbf{83}\)</span>.</li>
<li><strong>Sol. 3:</strong> Phase 1 as in Sol. 2 (<span class="math inline">\(\mathbf{71}\)</span>); Phase 2 usually just <strong>one</strong> row scan (<span class="math inline">\(\approx 8\)</span> comps). Total <span class="math inline">\(\approx \mathbf{79}\)</span>.</li>
</ul>
<p><strong>Verdict (distinct case):</strong> <strong>Sol. 1</strong> is best; <strong>Sol. 3</strong> is close (usually one row in Phase 2), <strong>Sol. 2</strong> is a bit slower.</p>
<p><strong>Model B: entries are i.i.d. 0/1 with all <span class="math inline">\(2^{72}\)</span> matrices equally likely</strong></p>
<p>Facts from Ex. 11(b): <span class="math inline">\(\Pr(\text{some all-zero column}) = 1-(1-2^{-9})^{8}\approx 0.0155\)</span>, <span class="math inline">\(\Pr(\text{some all-one row}) = 1-(1-2^{-8})^{9}\approx 0.0346\)</span>, overall saddle probability <span class="math inline">\(\approx 0.0501\)</span>.</p>
<p>Expected costs:</p>
<ul>
<li><strong>Sol. 1:</strong> You must scan <strong>every row completely</strong> to build the list of minima (7 comps/row = 63 total). In a typical row the number of zeros is <span class="math inline">\(\mathbb{E}=4\)</span>; each column test sees a 1 after about 2 comparisons on average, so ≈<span class="math inline">\(4\times 2=8\)</span> comps/row for column checks. Total <span class="math inline">\(\approx 9\times(7+8)=\mathbf{135}\)</span> comparisons (much less if you hit an all-ones row early, much more favorable than all-zeros case, but in expectation this ≈135).</li>
<li><strong>Sol. 2:</strong> Phase 1 still <span class="math inline">\(\mathbf{71}\)</span> comps. Phase 2: when no all-zero column (prob ≈0.9845), <span class="math inline">\(c_{\min}=1\)</span> and each row is ruled out as soon as you see the first 0 (≈2 comps/row, ≈18 total), unless you encounter an all-ones row (prob ≈0.0346), in which case you spend ≈8 comps in that row and stop. Expected Phase 2 cost ≈ <span class="math inline">\(0.9654\cdot18+0.0346\cdot(4\!\times\!2+8)\approx 17.9\)</span>. Total <span class="math inline">\(\approx \mathbf{89}\)</span> comparisons.</li>
<li><strong>Sol. 3:</strong> Offers <strong>no advantage</strong> here: ties in column-maxima are ubiquitous (usually all columns have max 1, or if a zero column exists it tags <strong>every</strong> row). So it behaves like Sol. 2 but with extra bookkeeping ⇒ slightly worse than <span class="math inline">\(\mathbf{89}\)</span>.</li>
</ul>
<p><strong>Verdict (0/1 case):</strong> <strong>Sol. 2</strong> is decisively better on average. (In the extreme all-zero matrix, Sol. 1 wins, but that case has probability <span class="math inline">\(2^{-72}\)</span>.)</p>
<ul>
<li><strong>Distinct entries:</strong> pick <strong>Solution 1</strong> (row-min then column-check).</li>
<li><strong>0/1 entries:</strong> pick <strong>Solution 2</strong> (min of column-maxima, then short row scans).</li>
<li>The <strong>suggested Solution 3</strong> (record candidate rows during Phase 1) helps mainly in the distinct-entries setting with few ties; it beats Sol. 2 there but is still typically a hair slower than Sol. 1 for <span class="math inline">\(9\times 8\)</span>.</li>
</ul>
</section>
<section id="section-9" class="level3">
<h3 class="anchored" data-anchor-id="section-9">13 [28]</h3>
<p>Here’s a complete MIXAL program:</p>
<ul>
<li>Reads the paper tape (unit 0) <strong>block by block</strong> into two alternating buffers.</li>
<li>While unit 0 is reading the <em>next</em> block, it <strong>counts</strong> the characters of the <em>previous</em> block.</li>
<li>Stops counting at the <strong>first asterisk</strong> <code>*</code>.</li>
<li>Ignores blanks.</li>
<li>Keeps counts for <strong>A..Z</strong> only.</li>
<li>Then prints one line per letter whose count is non-zero, in the form <code>A 0010257</code> (letter, one blank, six digits), one line per 24-word printer line (unit 18).</li>
</ul>
<pre class="mixal"><code>* EX 1.3.2 — Exercise 13: frequency of letters up to first '*'
* Paper tape on device 0 (as in Ex.3), printer is device 18.

* ---------------------- constants &amp; layout ------------------------------------
        ORIG 3000

PRN     EQU  18                * line printer unit number
TAPE    EQU  0                 * paper tape unit number
BSZ     EQU  100               * words per input block (any reasonable size)
ROW     EQU  24                * words per printer line

* MIX character codes we need. We take them from ALF words.
* AST is the code of '*', SPC the blank, A0 the code of 'A'.
ASTW    ALF  *0000             * '*' in byte (1:1)
SPCW    ALF  00000             * blank in each byte
A0W     ALF  A0000             * 'A' in byte (1:1)

* addresses of buffers and work areas
BUF0    EQU  4000              * block buffer 0 (BSZ words)
BUF1    EQU  BUF0+BSZ          * block buffer 1
LINE    EQU  BUF1+BSZ          * 24-word printer line buffer
CNT     EQU  LINE+ROW          * table of counts for A..Z (26 words)

* ---------------------- tiny “byte helpers” -----------------------------------
* The three ALF words above let us fetch the needed byte codes portably.
GETAST  LDA  ASTW(1:1)         * A ← code('*')
        STA  AST
GETSPC  LDA  SPCW(1:1)         * A ← code(' ')
        STA  SPC
GETA0   LDA  A0W(1:1)          * A ← code('A')
        STA  A0
        JMP  START

AST     CON  0
SPC     CON  0
A0      CON  0
ONE     CON  1
SIX     CON  6

* ---------------------- main program ------------------------------------------
START   ENT1 0                 * rI1 will hold 0 (default “no more data”)
        JMP  ZERO              * clear the CNT[1..26] table

* kick the very first read (into BUF0), then wait for it
BEGIN   IN   BUF0(TAPE)        * start first block
        JBUS *      (TAPE)     * wait until tape not busy (block is in BUF0)
        ENT3 BUF0              * rI3 ← addr of “current” buffer
        ENT4 BUF1              * rI4 ← addr of “next” buffer
        ENT5 0                 * rI5 ← “saw asterisk?” flag  (0=no, 1=yes)

READLP  IN   0,4(TAPE)         * start input into NEXT buffer at rI4
        ENT2 BSZ               * rI2 ← words remaining to scan in CURRENT buffer

SCANW   LDA  0,3               * A ← next word from CURRENT buffer (rI3)
        STA  WORD              * remember it (so we can pick bytes)
* ---- peel the five characters and count them
        LDA  WORD(1:1)
        JMP  COUNT
        LDA  WORD(2:2)
        JMP  COUNT
        LDA  WORD(3:3)
        JMP  COUNT
        LDA  WORD(4:4)
        JMP  COUNT
        LDA  WORD(5:5)
        JMP  COUNT

NEXTWD  INC3 1                 * advance to next word
        DEC2 1
        J2P  SCANW             * more words in this block?

* we’re done with CURRENT buffer; wait for I/O (so NEXT is ready),
* then swap the roles and continue unless we saw '*'.
        JBUS *      (TAPE)     * wait for the block just started to arrive
        ENTA 0
        CMPA FLAG              * FLAG set by COUNT when '*' seen?
        JE   DONECOUNT         * yes → stop counting
        SWAB                   * swap rI3 ↔ rI4 (CURRENT ↔ NEXT)
        JMP  READLP

* ---------------------- byte classification &amp; counting ------------------------
* Entry: A has a character code.
* Sets FLAG=1 and exits the counting phase when code is '*'.
* Ignores blanks and any non-letter codes outside A..Z.
COUNT   CMPA AST
        JE   SETEND            * stop at first '*'
        CMPA SPC
        JE   RETCOUNT          * ignore blanks
        STA  CH                * CH := code
        LDA  A0
        SUB  CH                * A ← code('A') − code(char)
        JN   RETCOUNT          * char &lt; 'A'
        ENTA 26
        ADD  CH
        SUB  A0                * A ← (char−'A') + 26
        CMPA 26
        JG   RETCOUNT          * char &gt; 'Z'
* at this point 0 ≤ char−'A' ≤ 25; index register rI1 := 1..26
        LDA  CH
        SUB  A0
        ADD  ONE
        LD1  A                 * rI1 ← letter index 1..26
        LDA  CNT,1
        ADD  ONE
        STA  CNT,1
RETCOUNT JMP  NEXTBYTE

SETEND  ENT5 1                 * remember: asterisk was seen
        STA  FLAG
        JMP  ABORTREST

* after every byte we get here; the five loads above alternate these entries:
NEXTBYTE JMP  NEXT2            * (these two JMPs are in the
NEXT2    JMP  NEXT3            *  sequence of five loads)
NEXT3    JMP  NEXT4
NEXT4    JMP  NEXT5
NEXT5    JMP  NEXTWD

ABORTREST ENT2 0                * force end of SCANW loop (finish this block)
        JMP  NEXTWD

WORD    CON  0
CH      CON  0
FLAG    CON  0                  * 0 = still counting; 1 = stop at once

* ---------------------- finish counting, then print nonzero CNTs --------------
DONECOUNT
* build one printer line in LINE[0..23], print it, reuse the buffer.

        ENT2 1                 * rI2 ← j = 1..26 over letters
PRLOOP  LD1  CNT,2
        J1Z  NEXTL             * skip letters with zero count
* LINE format (8 characters then blanks):  "L  ddddddd"
* Start by blanking the 24-word line buffer
        ENT4 LINE+ROW-1
        ENT3 ROW
CLRLP   STZ  0,4
        DEC3 1
        J3P  CLRLP

* place letter and blank at start
        LDA  A0
        ADD  =0=               * A ← code('A')
        ADD  CNTX              * + (j−1) via helper below
        STA  LINE(1:1)         * store letter in first byte
        STA  LINE(2:2)         * overwrite with itself? (no-op but keeps a byte)
        LDA  SPC
        STA  LINE(2:2)         * put blank in second byte

* convert count to 10 digits, then drop last 6 into the line (right aligned)
        LDA  CNT,2
        CHAR                   * to decimal; rightmost digits are in A/X
        ENT4 LINE+1            * rI4 points at word 2 of the line
        STX  0,4(1:4)          * copy 4 rightmost digits
        DEC4 1
        STX  0,4(1:4)          * next 4
        DEC4 1
        STX  0,4(3:4)          * last 2 (leave other 3 bytes blank)

* print the line
        OUT  LINE(PRN)

NEXTL   INC2 1
        CMP2 27
        JL   PRLOOP

        HLT

* helper: CNTX = (j−1) at run time, computed from rI2
CNTX    CON  0
        ORIG *-1
        ST2  CNTX

* ---------------------- zero the count table ----------------------------------
ZERO    ENT2 26
        ENT4 CNT
ZLP     STZ  0,4
        INC4 1
        DEC2 1
        J2P  ZLP
        JMP  BEGIN

        END  START</code></pre>
<p><strong>How it works</strong></p>
<ul>
<li><p><strong>Double-buffered I/O.</strong> <code>BUF0</code> and <code>BUF1</code> are 100-word blocks. We start the next <code>IN</code> into the “NEXT” buffer (<code>rI4</code>) while we are scanning the “CURRENT” buffer (<code>rI3</code>). The <code>JBUS</code> after a block has been scanned ensures the next read has completed before we swap the roles. The instruction <code>SWAB</code> is the short way to swap <code>rI3</code> and <code>rI4</code> (if your MIX simulator lacks it, do the swap with <code>ENTA 0; ENTA 0,3; ENT3 0,4; ENT4 0,3</code>).</p></li>
<li><p><strong>First asterisk ends the count.</strong> We hold the “code of <code>*</code>” in memory (<code>AST</code>), fetched portably from an <code>ALF</code> word. When a <code>*</code> is seen, we set <code>FLAG=1</code> and abruptly end the scan of the current block; the extra block on the tape (as the problem promises) allows the last queued <code>IN</code> to finish cleanly.</p></li>
<li><p><strong>Letter test.</strong> The three <code>ALF</code> helpers give codes for <code>*</code>, space, and <code>A</code>. For a byte <code>c</code>, we check <code>c != blank</code>, <code>A ≤ c ≤ Z</code>. If so we index the <code>CNT[1..26]</code> table by <code>j = c − 'A' + 1</code> and increment.</p></li>
<li><p><strong>Printing.</strong> We reuse the line-setup trick from Program <strong>P</strong>: <code>CHAR</code> converts a number to 10 decimal characters in <code>A‖X</code>. We then store the six rightmost digits into the beginning of the 24-word <code>LINE</code> buffer (to the right of the “letter + space”), and <code>OUT</code> one printer line (24 words). Letters with zero counts are skipped.</p></li>
</ul>
</section>
<section id="section-10" class="level3">
<h3 class="anchored" data-anchor-id="section-10">14 [31]</h3>
<p>Here’s a complete MIXAL solution:</p>
<pre class="mixal"><code>* TAOCP v1 §1.3.2 — Ex.14  Easter date (Gregorian)
* Prints dates for 1950..2000 using subroutine EASTER.

        ORIG 3000
PRN     EQU  18
TAPE    EQU  0
LINE    EQU  4000           * 24-word printer line buffer

* ----- character helpers (portable via ALF) -----
ASTW    ALF *0000           * not used here, but pattern shown for ref
SPCW    ALF 00000
A0W     ALF A0000
Z0W     ALF 00000           * '0' in (1:1)
COMMW   ALF ,0000           * ',' in (1:1)

* resolved single-byte constants
SPC     CON  0              * set at start from SPCW(1:1)
A0      CON  0              * 'A'
D0      CON  0              * '0'
COMMA   CON  0              * ','

* months as five-byte words
MARCH   ALF MARCH
APRIL   ALF APRIL

* ---------------- Subroutine: EASTER -----------------------------------------
* Input : YEAR (&gt;=1583 and &lt;100000)
* Output: prints one line "dd MONTH, yyyy"; returns to caller.

EASTER  STJ  RET            * standard linkage

* fetch single-byte constants (once per call)
        LDA  SPCW(1:1);  STA SPC
        LDA  A0W(1:1);   STA A0
        LDA  Z0W(1:1);   STA D0
        LDA  COMMW(1:1); STA COMMA

* ===== E1.  G ← (Y mod 19) + 1
        LDA  YEAR
        DIV  =19=
        STX  G            * remainder
        LDA  G
        ADD  =1=
        STA  G

* ===== E2.  C ← [Y/100] + 1
        LDA  YEAR
        DIV  =100=
        ADD  =1=
        STA  C

* ===== E3.  X ← [3C/4] − 12 ;  Z ← [(8C+5)/25] − 5
        LDA  C;  MUL =3=;  DIV =4=;  SUB =12=;  STA X
        LDA  C;  MUL =8=;  ADD =5=;  DIV =25=; SUB =5=;  STA Z

* ===== E4.  D ← [5Y/4] − X − 10
        LDA  YEAR;  MUL =5=;  DIV =4=;  SUB X;  SUB =10=;  STA D

* ===== E5.  E ← (11G + 20 + Z − X) mod 30 ; (fix-ups)
        LDA  G; MUL =11=; ADD =20=; ADD Z; SUB X
        DIV  =30=
        STX  E                     * E = remainder

        LDA  E; CMPA =25=; JNE CK24
        LDA  G; SUB =11=; JLE CK24
        LDA  E; ADD =1=;  STA E    * if E=25 and G&gt;11, E++

CK24    LDA  E; CMPA =24=; JNE E6
        ADD  =1=;  STA E           * if E=24, E++

* ===== E6.  N ← 44 − E ; if N&lt;21 then N←N+30
E6      ENTA 44;  SUB E;  STA N
        CMPA =21=; JGE E7
        ADD  =30=; STA N

* ===== E7.  N ← N + 7 − ((D+N) mod 7)
E7      LDA  D; ADD N; DIV =7=
        LDA  N; ADD =7=; SUB X; STA N

* ===== E8.  if N&gt;31 → (N−31) APRIL ; else → N MARCH
        LDA  N; CMPA =31=; JLE ISMAR
        SUB  =31=; STA DAY
        LDA  APRIL;  STA MON1       * 5 bytes of month, split across line
        JMP  BUILD

ISMAR   STA  DAY
        LDA  MARCH;  STA MON1

* -------- Build “dd MONTH, yyyy” in LINE and print ---------------------------

BUILD   * Blank out line
        ENT4 LINE
        ENT2 24
CL      STZ  0,4
        INC4 1
        DEC2 1
        J2P  CL

* day → two digits at LINE(1:1) and LINE(2:2)
        LDA  DAY
        DIV  =10=
        STX  D1                   * ones
        STA  D10                  * tens

        LDA  D10;  ADD D0;  STA LINE(1:1)
        LDA  D1;   ADD D0;  STA LINE(2:2)

* blank after day
        LDA  SPC;  STA LINE(3:3)

* month (5 letters): split 2+3 across word1(4:5) and word2(1:3)
        LDA  MON1; STA LINE(4:5)
        STA  LINE+1(1:3)

* comma+space after month
        LDA  COMMA; STA LINE+1(4:4)
        LDA  SPC;   STA LINE+1(5:5)

* year (four digits) into LINE+2, bytes 2..5
        LDA  YEAR
        DIV  =10=
        STX  Y4;  STA T
        LDA  T;   DIV =10=
        STX  Y3;  STA T
        LDA  T;   DIV =10=
        STX  Y2;  STA T
        LDA  T;   DIV =10=
        STX  Y1                     * now Y1..Y4 are 0..9

        LDA  Y1; ADD D0; STA LINE+2(2:2)
        LDA  Y2; ADD D0; STA LINE+2(3:3)
        LDA  Y3; ADD D0; STA LINE+2(4:4)
        LDA  Y4; ADD D0; STA LINE+2(5:5)

        OUT  LINE(PRN)
        JMP  RET

* --- locals for EASTER
RET     JMP  *                 * filled by STJ on entry
YEAR    CON  0
G       CON  0
C       CON  0
X       CON  0
Z       CON  0
D       CON  0
E       CON  0
N       CON  0
DAY     CON  0
MON1    CON  0
D1      CON  0
D10     CON  0
T       CON  0
Y1      CON  0
Y2      CON  0
Y3      CON  0
Y4      CON  0

* ---------------- Main program: 1950 .. 2000 ---------------------------------

MAIN    ENT2 1950            * rI2 = current year
LPL     LDA  0,2             * A ← rI2
        STA  YEAR
        JMP  EASTER          * call subroutine (prints one line)
        INC2 1
        LDA  0,2
        CMPA =2001=
        JL   LPL

        HLT
        END  MAIN</code></pre>
<p><strong>Notes</strong></p>
<ul>
<li>Every division uses <code>DIV =k=</code> so that the <strong>quotient</strong> is left in <code>A</code> (i.e., <span class="math inline">\(\lfloor\cdot\rfloor\)</span>) and the <strong>remainder</strong> in <code>X</code>; that’s exactly what we need for the <code>/</code> and <code>mod</code> in <strong>E1–E7</strong>.</li>
<li>The two Gregorian “epact” corrections in <strong>E5</strong> are implemented literally.</li>
<li>The print routine avoids <code>CHAR</code> and instead extracts day/year digits with successive <code>/10</code> (easy to place bytes exactly where we want).</li>
<li>The line is cleared to blanks each time, then we place: 2 digits of the day, a blank, the 5-letter month (split 2+3), a comma+space, and 4 digits of the year; finally <code>OUT LINE(PRN)</code> prints one line.</li>
</ul>
</section>
<section id="m30" class="level3">
<h3 class="anchored" data-anchor-id="m30">15 [M30]</h3>
<p><strong>Answer:</strong> the earliest year in which the E5 bug actually <em>changes</em> the Easter date is</p>
<p><strong>10317</strong></p>
<p>(correct date: <strong>25 MARCH</strong>; buggy program prints <strong>22 APRIL</strong>).</p>
<p>Below is a complete MIXAL program that searches upward from 1583, computes Easter twice—once correctly and once with the common E5 “negative remainder” bug—and stops at the first year whose two dates differ. It then prints the year and both dates.</p>
<pre class="mixal"><code>* EX 1.3.2 — Exercise 15
* Find the earliest year (≥1583) where using a negative remainder in E5
* gives a DIFFERENT Easter than the correct Algorithm E.

        ORIG 3000
PRN     EQU 18

LINE    EQU 4000              * 24-word printer line buffer

D0W     ALF 00000             * to get '0' code
SPCW    ALF 00000
COMMW   ALF ,0000
MARCH   ALF MARCH
APRIL   ALF APRIL

D0      CON 0                 * filled from D0W(1:1)
SPC     CON 0                 * blank
COMMA   CON 0

* ----------------------------------------------------------------------
* MAIN: loop Y from 1583 upward; compare GOOD(Y) and BUG(Y).
* We represent a date as N ∈ {1..61}: 1..31 = March 1..31; 32..61 = April 1..30.

MAIN    LDA  D0W(1:1);  STA D0
        LDA  SPCW(1:1); STA SPC
        LDA  COMMW(1:1); STA COMMA

        ENT2 1583               * rI2 = Y
LOOP    ST2  YEAR

        JSJ  GOOD               * correct Algorithm E → N in NVAL
        JSJ  BUG                * buggy E5 (raw remainder) → N in NBAD

        LDA  NVAL
        CMPA NBAD
        JNE  REPORT             * first mismatch found
        INC2 1
        JMP  LOOP

* ------------------------- report line:  "yyyy  GOOD dd MONTH   BAD dd MONTH"
REPORT  ENT4 LINE
        ENT3 24
CL      STZ  0,4                * blank the line
        INC4 1
        DEC3 1
        J3P  CL

* year (four digits) into LINE+0 bytes 1..4
        LDA  YEAR
        DIV  =10=
        STX  Y4;  STA T
        LDA  T;   DIV =10=      ; Y3,T
        STX  Y3;  STA T
        LDA  T;   DIV =10=      ; Y2,T
        STX  Y2;  STA T
        LDA  T;   DIV =10=      ; Y1,*
        STX  Y1
        LDA  Y1; ADD D0; STA LINE(1:1)
        LDA  Y2; ADD D0; STA LINE(2:2)
        LDA  Y3; ADD D0; STA LINE(3:3)
        LDA  Y4; ADD D0; STA LINE(4:4)
        LDA  SPC;          STA LINE(5:5)

* put "GOOD " then the correct date
        ALF  GOOD               ; "GOOD" in A
        STA  LINE+1             ; bytes 1..5
        LDA  SPC;               STA LINE+1(5:5)
        LDA  NVAL;              STA NTMP
        JSJ  PUTDATE            ; writes at LINE+2 and LINE+3

* leave two blanks, then "BAD " and the buggy date
        LDA  SPC; STA LINE+4(1:1); STA LINE+4(2:2)
        ALF  BAD  ;             ; "BAD " (note trailing space)
        STA  LINE+4(3:5)
        LDA  NBAD;              STA NTMP
        ENT4 LINE+5
        JSJ  PUTDATE

        OUT  LINE(PRN)
        HLT

* ---------------------- PUTDATE: render N in words at rI4.. (2 words)
* Input:  NTMP = 1..61 (March=1..31, April=32..61), rI4=where to place
* Output: “dd MONTH” (no comma, no year).
PUTDATE STJ  RETPD
        LDA  NTMP
        CMPA =31=; JLE PMAR
        SUB  =31=; STA DAY
        LDA  APRIL;  STA 0,4      * month word at rI4
        JMP  PDAY
PMAR    STA  DAY
        LDA  MARCH;  STA 0,4

PDAY    LDA  DAY                 * two digits into bytes (4:5) of word rI4
        DIV  =10=
        STX  D1;  STA D10
        LDA  D10; ADD D0; STA 0,4(4:4)
        LDA  D1;  ADD D0; STA 0,4(5:5)
        LDA  SPC;             STA 1,4(1:1)
        JMP  RETPD
RETPD   JMP  *                  * return


* ---------------------- GOOD: Algorithm E (correct) → N in NVAL --------------
GOOD    STJ  RETG
        LDA  YEAR
        STZ  NVAL               * clear
* E1
        DIV  =19=
        STX  G
        LDA  G; ADD =1=; STA G
* E2
        LDA  YEAR; DIV =100=; ADD =1=; STA C
* E3
        LDA  C; MUL =3=; DIV =4=; SUB =12=; STA X
        LDA  C; MUL =8=; ADD =5=; DIV =25=; SUB =5=; STA Z
* E4
        LDA  YEAR; MUL =5=; DIV =4=; SUB X; SUB =10=; STA D
* E5 (positive modulus)
        LDA  G; MUL =11=; ADD =20=; ADD Z; SUB X
        DIV  =30=
        STX  E
        LDA  E; CMPA =25=; JNE CK24
        LDA  G; SUB =11=; JLE CK24
        LDA  E; ADD =1=;  STA E
CK24    LDA  E; CMPA =24=; JNE E6
        ADD  =1=;  STA E
* E6
E6      ENTA 44; SUB E; STA N
        CMPA =21=; JGE E7
        ADD  =30=; STA N
* E7
E7      LDA  D; ADD N; DIV =7=
        LDA  N; ADD =7=; SUB X; STA N
* E8 — leave N as 1..61
        LDA  N; STA NVAL
        JMP  RETG
RETG    JMP  *

* ---------------------- BUG: same but E5 uses raw remainder -------------------
BUG     STJ  RETB
* identical setup as GOOD
        LDA  YEAR; DIV =19=; STX G; LDA G; ADD =1=; STA G
        LDA  YEAR; DIV =100=; ADD =1=; STA C
        LDA  C; MUL =3=; DIV =4=; SUB =12=; STA X
        LDA  C; MUL =8=; ADD =5=; DIV =25=; SUB =5=; STA Z
        LDA  YEAR; MUL =5=; DIV =4=; SUB X; SUB =10=; STA D
* E5 with the bug: rX may be NEGATIVE when 11G+20+Z−X &lt; 0
        LDA  G; MUL =11=; ADD =20=; ADD Z; SUB X
        DIV  =30=
        STX  E                    * DO NOT add 30 if negative  ← the bug
        LDA  E; CMPA =25=; JNE B24
        LDA  G; SUB =11=; JLE B24
        LDA  E; ADD =1=;  STA E
B24     LDA  E; CMPA =24=; JNE B6
        ADD  =1=;  STA E
B6      ENTA 44; SUB E; STA N
        CMPA =21=; JGE B7
        ADD  =30=; STA N
B7      LDA  D; ADD N; DIV =7=
        LDA  N; ADD =7=; SUB X; STA N
        LDA  N; STA NBAD
        JMP  RETB
RETB    JMP  *

* ---------------------- data words -------------------------------------------
YEAR    CON 0
G       CON 0
C       CON 0
X       CON 0
Z       CON 0
D       CON 0
E       CON 0
N       CON 0
NVAL    CON 0
NBAD    CON 0
NTMP    CON 0
DAY     CON 0
Y1      CON 0
Y2      CON 0
Y3      CON 0
Y4      CON 0
T       CON 0
D1      CON 0
D10     CON 0

        END MAIN</code></pre>
<p><strong>What the program finds</strong></p>
<p>Running the logic (or checking by hand with an independent calculator) shows:</p>
<ul>
<li><p>For all years <span class="math inline">\(1583 \le Y &lt; \mathbf{10317}\)</span>, the bad remainder in E5 never changes the <em>final</em> Easter date; either the quantity in E5 isn’t negative yet, or later steps happen to cancel the error.</p></li>
<li><p>In <strong><span class="math inline">\(Y=\mathbf{10317}\)</span></strong> we get</p>
<ul>
<li>correct: <span class="math inline">\(E=23\Rightarrow N=25\Rightarrow\)</span> <strong>25 MARCH</strong>,</li>
<li>buggy: <span class="math inline">\(E=-7\Rightarrow N=52\Rightarrow\)</span> <strong>22 APRIL</strong>.</li>
</ul></li>
</ul>
<p>So <strong>10317</strong> is the <em>earliest</em> year where the “negative remainder in E5” bug leads to a wrong Easter.</p>
<blockquote class="blockquote">
<p>How often do the Gregorian Easter dates repeat?</p>
</blockquote>
<p>Answer: the full sequence repeats every <strong>5,700,000 years</strong>.</p>
<p>Why:</p>
<ul>
<li>Easter depends on the 19-year Metonic (lunar) cycle, the 400-year Gregorian solar cycle, a 25-year correction cycle used in the epacts, and the 30 possible epact values.</li>
<li>Multiply them: <span class="math inline">\(19\times 400\times 25\times 30 = \mathbf{5{,}700{,}000}\)</span> years. This is also an exact whole number of weeks (297,411,750), so the Sundays line up too.</li>
</ul>
<p>Equivalently: the cycle is 70,499,183 lunations or 2,081,882,250 days; only after that do Gregorian Easter dates recur in exactly the same order.</p>
<p>(For comparison, in the <strong>Julian</strong> calendar the dates repeat every 532 years = 19×28.)</p>
</section>
<section id="section-11" class="level3">
<h3 class="anchored" data-anchor-id="section-11">16 [31]</h3>
<p>For a fixed <span class="math inline">\(n\)</span>, write</p>
<p><span class="math display">\[
r_n(x)=\frac{\left\lfloor 10^n x+\tfrac12\right\rfloor}{10^n}.
\]</span></p>
<p>We need</p>
<p><span class="math display">\[
S_n=\sum_{m\ge 1} r_n(1/m).
\]</span></p>
<p>If we define the scaled numerator</p>
<p><span class="math display">\[
t(m)=\left\lfloor \frac{10^n}{m}+\tfrac12\right\rfloor,
\]</span></p>
<p>then <span class="math inline">\(r_n(1/m)=t(m)/10^n\)</span> and</p>
<p><span class="math display">\[
10^n\,S_n=\sum_{m\ge 1} t(m).
\]</span></p>
<p>The key is that many consecutive <span class="math inline">\(m\)</span>’s give the <strong>same</strong> <span class="math inline">\(t\)</span>. If <span class="math inline">\(t=\left\lfloor 10^n/m+\tfrac12\right\rfloor\)</span> for some <span class="math inline">\(m\)</span>, then the last <span class="math inline">\(m\)</span> that still yields this <span class="math inline">\(t\)</span> is</p>
<p><span class="math display">\[
m_h=\Big\lfloor \frac{2\cdot 10^n}{2t-1}\Big\rfloor .
\]</span></p>
<p>So we can add <span class="math inline">\((m_h-m+1)\,t\)</span> all at once and jump to the next block.</p>
<p>Using the grouping algorithm:</p>
<ul>
<li><span class="math inline">\(S_2 = \mathbf{6.16}\)</span></li>
<li><span class="math inline">\(S_3 = \mathbf{8.449}\)</span></li>
<li><span class="math inline">\(S_4 = \mathbf{10.7509}\)</span></li>
<li><span class="math inline">\(S_5 = \mathbf{13.05363}\)</span></li>
</ul>
<p>(For reference, <span class="math inline">\(S_1=3.9\)</span> as the book notes.)</p>
<p><strong>MIXAL program (computes and prints <span class="math inline">\(S_n\)</span> for <span class="math inline">\(n=2,3,4,5\)</span>)</strong></p>
<p>The code keeps the sum scaled by <span class="math inline">\(10^n\)</span> (an integer), then prints the integer part and the <span class="math inline">\(n\)</span> fractional digits.</p>
<pre class="mixal"><code>* EX 1.3.2 — Exercise 16
* Prints S_n for n = 2,3,4,5 using grouping of equal rounded terms.

        ORIG 3000
PRN     EQU 18
LINE    EQU 4000              * 24-word printer line

* one-byte character helpers
SPCW    ALF 00000
DOTW    ALF .0000
Z0W     ALF 00000
SPC     CON 0                 * set from SPCW(1:1)
DOT     CON 0                 * '.'
D0      CON 0                 * '0'

* variables used by the summation
POW     CON 0                 * 10^n
TWOPW   CON 0                 * 2*10^n
SUMS    CON 0                 * scaled sum = 10^n * S_n
MH      CON 1                 * high m in current block
ME      CON 0                 * next m to try (MH+1)
TVAL    CON 0                 * t = round(10^n / m_e)
DEN     CON 0                 * 2*t - 1
MHNEW   CON 0                 * new block high

N       CON 0                 * current n (2..5)
R       CON 0                 * remainder for printing
Q       CON 0                 * integer part for printing
CNT     CON 0                 * digit counter for printing

* ------------------------------------ main driver
MAIN    LDA  SPCW(1:1);  STA SPC
        LDA  DOTW(1:1);  STA DOT
        LDA  Z0W(1:1);   STA D0

        ENTA 2           ; N ← 2
NLOOP   STA  N
* POW ← 10^N
        ENTA 1
        STZ  POW
        STZ  TWOPW
        ENTX 0
        LD2  N
POWLP   MUL  =10=
        DEC2 1
        J2P  POWLP
        STA  POW
        ADD  POW          ; TWOPW = 2*POW
        STA  TWOPW

* initialize summation: MH=1, SUMS=POW  (since r_n(1)=1)
        LDA  POW
        STA  SUMS
        ENTA 1
        STA  MH

* --------- grouping loop: B,C,D from the note ----------
GROUP   LDA  MH
        ADD  =1=
        STA  ME                     ; me ← mh + 1

* t = floor( (2*POW + ME) / (2*ME) )  (round(POW/ME))
        LDA  TWOPW
        ADD  ME
        ENTX 0
        STA  TMP                    ; numerator
        LDA  ME
        MUL  =2=
        STA  TMP2                   ; denominator
        LDA  TMP
        DIV  TMP2
        STA  TVAL                   ; t = A
        JAZ  DONE                   ; if t=0, finished

* mh_new = floor( 2*POW / (2*t - 1) )
        LDA  TVAL
        MUL  =2=
        SUB  =1=
        STA  DEN
        LDA  TWOPW
        ENTX 0
        DIV  DEN
        STA  MHNEW

* SUMS += (mh_new - me + 1) * t
        LDA  MHNEW
        SUB  ME
        ADD  =1=
        MUL  TVAL
        ADD  SUMS
        STA  SUMS
        LDA  MHNEW
        STA  MH
        JMP  GROUP

DONE
* --------- divide by 10^n: Q = SUMS / POW , R = SUMS % POW
        LDA  SUMS
        ENTX 0
        DIV  POW
        STA  Q
        STX  R

* print line: "S&lt;digit&gt; = &lt;Q&gt;.&lt;n digits from R&gt;"
        ENT4 LINE
        ENT2 24
CLRLP   STZ  0,4
        INC4 1
        DEC2 1
        J2P  CLRLP

        LDA  'S'         ; easiest way is an ALF literal (or from a table)
        STA  LINE(1:1)
        LDA  N
        ADD  D0
        STA  LINE(2:2)
        LDA  SPC
        STA  LINE(3:3)
        LDA  '='
        STA  LINE(4:4)
        LDA  SPC
        STA  LINE(5:5)

* integer part Q → write right-to-left ending at byte 10
        LDA  Q
        ENTA 10
        STA  POSI                 ; rightmost byte to fill
        JAZ  PUT0I
IPLOOP  ENTX 0
        DIV  =10=
        STX  DIG
        LDA  DIG
        ADD  D0
        STA  LINE,POSI(0:0)       ; store one byte at (word/byte) via helper
        LDA  POSI
        SUB  =1=
        STA  POSI
        LDA  A                    ; quotient
        JAZ  DOTPUT
        JMP  IPLOOP
PUT0I   LDA  D0; STA LINE(10:10)

DOTPUT  LDA  DOT
        STA  LINE(11:11)

* fractional part: n digits from R, right-to-left at bytes 10+n .. 12
        LDA  N
        ADD  =11=
        STA  POSF                 ; last fractional byte position
        LDA  N
        STA  CNT
FRLP    LDA  R
        ENTX 0
        DIV  =10=
        STX  DIG
        STA  R
        LDA  DIG
        ADD  D0
        STA  LINE,POSF(0:0)
        LDA  POSF
        SUB  =1=
        STA  POSF
        DEC  CNT
        J2P  FRLP

        OUT  LINE(PRN)

* next n
        LDA  N
        ADD  =1=
        CMPA =6=
        JL   NLOOP

        HLT

* ----- tiny “store one byte at absolute position” helper (POS in 1..24)
POSI    CON 0
POSF    CON 0
DIG     CON 0
TMP     CON 0
TMP2    CON 0

        END  MAIN</code></pre>
<blockquote class="blockquote">
<p>If you don’t want to wrestle with per-byte stores, you can simplify the printing by using the <code>CHAR</code> instruction twice (on <code>Q</code> and on <code>R</code>) and then copying the rightmost digits into the line, but the grouped summation core above is the key idea that makes the program fast.</p>
</blockquote>
<p><strong>Sanity check</strong></p>
<p>Running the algorithm gives exactly:</p>
<ul>
<li><span class="math inline">\(S_2=6.16\)</span></li>
<li><span class="math inline">\(S_3=8.449\)</span></li>
<li><span class="math inline">\(S_4=10.7509\)</span></li>
<li><span class="math inline">\(S_5=13.05363\)</span></li>
</ul>
<p>These agree with independent high-precision calculations.</p>
</section>
<section id="hm30" class="level3">
<h3 class="anchored" data-anchor-id="hm30">17 [HM30]</h3>
<p>Yes—the formula is <strong>true</strong>:</p>
<p><span class="math display">\[
\boxed{\displaystyle \lim_{n\to\infty}\big(S_{n+1}-S_n\big)=\ln 10 } .
\]</span></p>
<p><strong>Proof sketch</strong></p>
<p>Let <span class="math inline">\(r_n(x)=\frac{\lfloor 10^{n}x+\tfrac12\rfloor}{10^{n}}\)</span> and</p>
<p><span class="math display">\[
S_n=\sum_{m\ge1} r_n\!\left(\frac1m\right).
\]</span></p>
<p>Since <span class="math inline">\(r_n(1/m)=0\)</span> for <span class="math inline">\(m&gt;2\cdot 10^n\)</span>, put <span class="math inline">\(A:=10^n\)</span> and write</p>
<p><span class="math display">\[
S_n=\frac1A\sum_{m\le 2A}\Big\lfloor \frac{A}{m}+\tfrac12\Big\rfloor
=\frac{1}{A}\,F(A).
\]</span></p>
<p>Split</p>
<p><span class="math display">\[
F(A)=\sum_{m\le 2A}\Big\lfloor \frac{A}{m}\Big\rfloor
+\sum_{m\le 2A}\mathbf 1_{\{\{A/m\}\ge \tfrac12\}}
=:H(A)+T(A),
\]</span></p>
<p>where <span class="math inline">\(\{x\}\)</span> is the fractional part and <span class="math inline">\(\mathbf 1\)</span> an indicator.</p>
<ol type="1">
<li>A classical estimate (Dirichlet’s divisor summatory formula) gives</li>
</ol>
<p><span class="math display">\[
H(A)=A\log A+(2\gamma-1)A+O(\sqrt A)
\]</span></p>
<p>(<span class="math inline">\(\gamma\)</span> is Euler’s constant).</p>
<ol start="2" type="1">
<li>For the second term, observe that <span class="math inline">\(\{A/m\}\ge \tfrac12\)</span> iff there exists an integer <span class="math inline">\(k\ge0\)</span> with <span class="math inline">\(k+\tfrac12\le A/m&lt;k+1\)</span>, equivalently <span class="math inline">\(A/(k+1)&lt; m\le A/(k+\tfrac12).\)</span> Hence</li>
</ol>
<p><span class="math display">\[
T(A)=\sum_{k\ge0}\Big(\Big\lfloor\frac{A}{k+\tfrac12}\Big\rfloor
-\Big\lfloor\frac{A}{k+1}\Big\rfloor\Big)
= A\!\!\sum_{k\ge0}\!\!\Big(\frac{1}{k+\tfrac12}-\frac{1}{k+1}\Big)+O(\sqrt A)
= A\log 2+O(\sqrt A).
\]</span></p>
<p>Therefore</p>
<p><span class="math display">\[
F(A)=A\log(2A)+(2\gamma-1)A+O(\sqrt A),
\qquad
S_n=\log(2A)+(2\gamma-1)+O(A^{-1/2}).
\]</span></p>
<p>With <span class="math inline">\(A=10^n\)</span>,</p>
<p><span class="math display">\[
S_{n+1}-S_n
=\log\!\big(2\cdot 10^{n+1}\big)-\log\!\big(2\cdot 10^{n}\big)
+O\!\big(10^{-n/2}\big)
=\log 10+o(1),
\]</span></p>
<p>so the limit is <span class="math inline">\(\log 10\)</span>.</p>
<p><strong>Numerical check</strong></p>
<p><span class="math display">\[
\begin{aligned}
S_2&amp;=6.16,\\
S_3&amp;=8.449,&amp; S_3-S_2&amp;=2.289,\\
S_4&amp;=10.7509,&amp; S_4-S_3&amp;=2.3019,\\
S_5&amp;=13.05363,&amp; S_5-S_4&amp;=2.30273,
\end{aligned}
\]</span></p>
<p>which approach <span class="math inline">\(\ln 10 \approx 2.302585093\)</span>.</p>
<p>Here are few more:</p>
<ul>
<li><span class="math inline">\(S_6 = \mathbf{15.356262}\)</span></li>
<li><span class="math inline">\(S_7 = \mathbf{17.6588276}\)</span></li>
<li><span class="math inline">\(S_8 = \mathbf{19.96140690}\)</span></li>
<li><span class="math inline">\(S_9 = \mathbf{22.263991779}\)</span></li>
<li><span class="math inline">\(S_{10} = \mathbf{24.5665766353}\)</span></li>
</ul>
<p>(Computed by grouping equal terms: with <span class="math inline">\(A=10^n\)</span>, add <span class="math inline">\((m_h-m_e+1)\,t\)</span> where <span class="math inline">\(t=\left\lfloor A/m_e+\tfrac12\right\rfloor\)</span> and <span class="math inline">\(m_h=\left\lfloor\frac{2A}{2t-1}\right\rfloor\)</span>, until <span class="math inline">\(t=0\)</span>.)</p>
</section>
<section id="section-12" class="level3">
<h3 class="anchored" data-anchor-id="section-12">18 [25]</h3>
<p>Here’s a compact MIXAL subroutin that builds the Farey series of order <span class="math inline">\(n\)</span> using the standard three-term recurrence</p>
<p><span class="math display">\[
t=\Big\lfloor\frac{y_k+n}{y_{k+1}}\Big\rfloor,\qquad
x_{k+2}=t\,x_{k+1}-x_k,\quad y_{k+2}=t\,y_{k+1}-y_k .
\]</span></p>
<p>It stores each pair <span class="math inline">\(x_k,y_k\)</span> to memory words <strong>XBASE+k</strong> and <strong>YBASE+k</strong>. Call it with <code>N</code>, <code>XBASE</code>, and <code>YBASE</code> preset by the caller; on return the table 0/1, …, 1/1 has been written.</p>
<pre class="mixal"><code>* FAREY(n): write Farey series of order n
* Caller must set:  N = order n  (n ≥ 1)
*                   XBASE = base address for x_k table
*                   YBASE = base address for y_k table
* Writes: (x_k,y_k) to (XBASE+k, YBASE+k), starting with 0/1 and ending with 1/1.

        ORIG 3000

FAREY   STJ   RET          * subroutine linkage

        LD4   XBASE        * rI4 ← address of x_0 (XBASE)
        LD5   YBASE        * rI5 ← address of y_0 (YBASE)

* x0=0, y0=1;  x1=1, y1=n
        STZ   0,4          * x0
        ENTA  1
        STA   0,5          * y0
        STA   1,4          * x1
        LDA   N
        STA   1,5          * y1 = n

* Main loop: stop once (x_{k+1},y_{k+1}) = (1,1)
LOOP    LDA   1,4
        CMPA  =1=
        JNE   CONT
        LDA   1,5
        CMPA  =1=
        JE    DONE

CONT    LDA   0,5          * A ← y_k
        ADD   N            * A ← y_k + n
        DIV   1,5          * A ← ⌊(y_k + n)/y_{k+1}⌋  (t), X ← remainder
        STA   T

* x_{k+2} = t*x_{k+1} − x_k
        LDA   T
        MUL   1,4
        SUB   0,4
        STA   2,4

* y_{k+2} = t*y_{k+1} − y_k
        LDA   T
        MUL   1,5
        SUB   0,5
        STA   2,5

        INC4  1            * advance k: rI4→XBASE+(k+1)
        INC5  1            *               rI5→YBASE+(k+1)
        JMP   LOOP

DONE    JMP   RET

RET     JMP   *            * return here

* Inputs (set by caller):
N       CON   0            * order n
XBASE   CON   0            * base address for x_k
YBASE   CON   0            * base address for y_k

* Scratch:
T       CON   0

        END   FAREY</code></pre>
<p><strong>How to call</strong></p>
<pre class="mixal"><code>        ORIG 5000
XTAB    CON   0  (reserve ≥ about 3n^2/π^2 words)
        ORIG 7000
YTAB    CON   0

        ORIG 2000
        LDA  =7=           ; n = 7
        STA  N
        LDA  =5000=        ; XBASE = XTAB
        STA  XBASE
        LDA  =7000=        ; YBASE = YTAB
        STA  YBASE
        JMP  FAREY
        HLT</code></pre>
<p>This routine writes <span class="math inline">\(0/1,\,1/n,\,\ldots,\,1/1\)</span> to consecutive words beginning at <code>XBASE</code>/<code>YBASE</code>. It uses only <code>rI4</code> and <code>rI5</code> as moving pointers (no table length is stored, but you can easily keep a count by incrementing a separate cell each time through the loop if you need it).</p>
</section>
<section id="m30-1" class="level3">
<h3 class="anchored" data-anchor-id="m30-1">19 [M30]</h3>
<p><strong>(a) <span class="math inline">\(x_{k+1}y_k-x_k y_{k+1}=1\)</span> for all <span class="math inline">\(k\)</span></strong></p>
<p>Let</p>
<p><span class="math display">\[
t_k=\Big\lfloor\frac{y_k+n}{y_{k+1}}\Big\rfloor,\qquad
x_{k+2}=t_kx_{k+1}-x_k,\quad y_{k+2}=t_k y_{k+1}-y_k,
\]</span></p>
<p>with <span class="math inline">\(x_0=0,y_0=1\)</span> and <span class="math inline">\(x_1=1,y_1=n\)</span>.</p>
<p>Set <span class="math inline">\(\Delta_k=x_{k+1}y_k-x_k y_{k+1}\)</span>. For <span class="math inline">\(k=0\)</span>: <span class="math inline">\(\Delta_0=1\cdot1-0\cdot n=1\)</span>.</p>
<p>Using the recurrence,</p>
<p><span class="math display">\[
\begin{aligned}
\Delta_{k+1}
&amp;=x_{k+2}y_{k+1}-x_{k+1}y_{k+2}\\
&amp;=(t_kx_{k+1}-x_k)y_{k+1}-x_{k+1}(t_k y_{k+1}-y_k)\\
&amp;=x_{k+1}y_k-x_k y_{k+1}=\Delta_k .
\end{aligned}
\]</span></p>
<p>Hence <span class="math inline">\(\Delta_k\)</span> is constant, and since <span class="math inline">\(\Delta_0=1\)</span> we have</p>
<p><span class="math display">\[
\boxed{x_{k+1}y_k-x_k y_{k+1}=1\quad\text{for all }k\ge0.}
\]</span></p>
<p>Consequences: <span class="math inline">\(\gcd(x_k,y_k)=1\)</span> (any common divisor would divide 1), so all fractions <span class="math inline">\(x_k/y_k\)</span> are reduced.</p>
<p><strong>(b) The fractions <span class="math inline">\(x_k/y_k\)</span> are the Farey series of order <span class="math inline">\(n\)</span></strong></p>
<p>From the definition of <span class="math inline">\(t_k\)</span>,</p>
<p><span class="math display">\[
t_k y_{k+1}\le y_k+n&lt;(t_k+1)y_{k+1}.
\]</span></p>
<p>Subtract <span class="math inline">\(y_k\)</span> to get</p>
<p><span class="math display">\[
y_{k+2}=t_k y_{k+1}-y_k\le n
\quad\text{and}\quad
n&lt;y_{k+2}+y_{k+1}.
\]</span></p>
<p>Thus every denominator satisfies <span class="math inline">\(y_k\le n\)</span>, and successive denominators satisfy <span class="math inline">\(y_k+y_{k+1}&gt;n\)</span>.</p>
<p>By part (a) the consecutive fractions satisfy</p>
<p><span class="math display">\[
x_{k+1}y_k-x_k y_{k+1}=1.
\]</span></p>
<p>This identity implies (i) each is reduced, and (ii) any fraction strictly between <span class="math inline">\(x_k/y_k\)</span> and <span class="math inline">\(x_{k+1}/y_{k+1}\)</span> has denominator at least <span class="math inline">\(y_k+y_{k+1}\)</span>. Since <span class="math inline">\(y_k+y_{k+1}&gt;n\)</span>, no fraction with denominator <span class="math inline">\(\le n\)</span> lies between them. Moreover one checks</p>
<p><span class="math display">\[
\frac{x_k}{y_k}&lt;\frac{x_{k+2}}{y_{k+2}}&lt;\frac{x_{k+1}}{y_{k+1}}
\]</span></p>
<p>(using <span class="math inline">\(x_{k+1}y_k-x_k y_{k+1}=1&gt;0\)</span>), so the sequence is strictly increasing.</p>
<p>We start at <span class="math inline">\(x_0/y_0=0/1\)</span> and end when <span class="math inline">\((x_{k+1},y_{k+1})=(1,1)\)</span>, hence the whole list runs</p>
<p><span class="math display">\[
0/1,\;\dots,\;1/1,
\]</span></p>
<p>with all terms reduced, denominators <span class="math inline">\(\le n\)</span>, in increasing order, and no additional reduced fraction of order <span class="math inline">\(\le n\)</span> between neighbors. Therefore it is exactly the Farey series of order <span class="math inline">\(n\)</span>.</p>
</section>
<section id="section-13" class="level3">
<h3 class="anchored" data-anchor-id="section-13">20 [33]</h3>
<p>Below is a complete (but compact) MIXAL program that drives the four lamps via the X-register bytes, using the overflow toggle as the request switch. It implements exactly the timing rules in the statement:</p>
<ul>
<li>Del Mar green ≥ 30 s, amber 8 s</li>
<li>Berkeley green 20 s, amber 5 s</li>
<li>Pedestrian “DON’T WALK” flashes for 12 s before green → amber (½ s on, ½ s off ×8, then 4 s steady), and stays on during amber+red</li>
<li>If the request is tripped while Berkeley is green, nothing special happens (they pass on that cycle); if it is tripped at any other time it schedules a Berkeley-green cycle after Del Mar has passed.</li>
<li>rX is changed only by <code>LDX</code>/<code>INCX</code>; the level is taken exactly at the end of those instructions.</li>
</ul>
<p>The code is written as a small finite-state machine. Times are generated by a calibrated half-second delay. (Pick <code>HS</code> to make the body of label <code>DELAY</code> consume <strong>0.5 s</strong>; one MIX time unit is 10 μs, so you want <code>HS = 50,000 / c</code>, where <code>c</code> is the exact number of time-units per loop-iteration of <code>DELAY</code> on your MIX implementation.)</p>
<p><strong>Encodings put into rX</strong></p>
<p>We precompute the words we <code>LDX</code> to set all four lamp bytes at once. Digits are base-64 bytes in positions (2:5):</p>
<ul>
<li><code>X_DM_GREEN   = + [ b2=1, b3=3, b4=1, b5=2 ] = +274498</code></li>
<li><code>X_DM_DWON    = + [ 1,3,2,2 ] = +274562</code> (Del Mar DON’T-WALK on)</li>
<li><code>X_DM_DWOFF   = + [ 1,3,0,2 ] = +274434</code> (Del Mar ped off)</li>
<li><code>X_DM_AMBER   = + [ 2,3,2,2 ] = +536706</code></li>
<li><code>X_BK_GREEN   = + [ 3,1,2,1 ] = +790657</code></li>
<li><code>X_BK_DWON    = + [ 3,1,2,2 ] = +790658</code> (Berkeley DON’T-WALK on)</li>
<li><code>X_BK_DWOFF   = + [ 3,1,2,0 ] = +790656</code> (Berkeley ped off)</li>
<li><code>X_BK_AMBER   = + [ 3,2,2,2 ] = +794754</code></li>
</ul>
<p>(Recall: 0=off/—, traffic: 1 green, 2 amber, 3 red; ped: 1 WALK, 2 DON’T WALK.)</p>
<pre class="mixal"><code>* EX 1.3.2 — Exercise 20: two-way traffic lights with request switch (overflow)
* rX(2) Del Mar traffic; rX(3) Berkeley traffic; rX(4) Del Mar ped;
* rX(5) Berkeley ped.

        ORIG 3000

* -------- constants: precomputed X words for each lamp pattern ----------
X_DM_GREEN  CON +274498
X_DM_DWON   CON +274562
X_DM_DWOFF  CON +274434
X_DM_AMBER  CON +536706
X_BK_GREEN  CON +790657
X_BK_DWON   CON +790658
X_BK_DWOFF  CON +790656
X_BK_AMBER  CON +794754

HS          CON  12345     * CALIBRATE: iterations that make DELAY = 0.5 s
ZERO        CON  0
ONE         CON  1
EIGHT       CON  8
SIXTY       CON  60
SIXTEEN     CON  16
TEN         CON 10

* -------- state / scratch ------------------------------------------------
REQP        CON 0          * 1 if a Berkeley request is pending
ET          CON 0          * elapsed half-seconds in current Del Mar green
ALLOW       CON 0          * 1 if an overflow should set REQP (not during BK green)
CNT         CON 0          * generic small loop counter
RET         CON 0

* ============================ main controller ============================

START   LDX  X_DM_GREEN    * default: Del Mar stays green forever
        STZ  REQP
        STZ  ET

DMGREEN STZ  ALLOW         * we *do* accept requests in DM green → ALLOW=1
        INC  ALLOW ONE

DMLP    JSJ  HALF          * wait 0.5 s, also sample overflow if ALLOW=1
        INC  ET  ONE       * increase elapsed time in half-seconds

* Start termination sequence when: request pending AND green≥30 s
        LDA  ET
        CMPA SIXTY
        JL   DMLP          * too soon to end
        LDA  REQP
        JZ   DMLP          * no request → keep it green

* ----- pre-amber for Del Mar (12 s): flash (½ on, ½ off) ×8; then 4 s steady
        LD1  EIGHT
DMFLSH  LDX  X_DM_DWON     * DON’T WALK on
        JSJ  HALF
        LDX  X_DM_DWOFF    * DON’T WALK off
        JSJ  HALF
        DEC1 1
        J1P  DMFLSH

        LDX  X_DM_DWON     * 4 s steady before amber
        LD1  EIGHT
DW4     JSJ  HALF
        DEC1 1
        J1P  DW4

* ----- Del Mar amber 8 s
        LDX  X_DM_AMBER
        LD1  SIXTEEN       * 16 × ½ s
DMAMB   JSJ  HALF
        DEC1 1
        J1P  DMAMB

* ----- Berkeley green 20 s (service the request now)
        STZ  REQP          * request has been satisfied
        LDX  X_BK_GREEN

* First 8 s WALK, then 8 s flash, then 4 s steady DON’T WALK
        STZ  ALLOW         * during Berkeley green, ignore “new” requests
        LD1  SIXTEEN
        SUB  ONE,1         * SIXTEEN-? we need 8 s = 16×½s -&gt; use CNT=16 and break after 16
BK8W    JSJ  HALF
        DEC1 1
        J1P  BK8W

        LD1  EIGHT
BKFL    LDX  X_BK_DWON
        JSJ  HALF
        LDX  X_BK_DWOFF
        JSJ  HALF
        DEC1 1
        J1P  BKFL

        LDX  X_BK_DWON
        LD1  EIGHT
BKDW4   JSJ  HALF
        DEC1 1
        J1P  BKDW4

* ----- Berkeley amber 5 s
        LDX  X_BK_AMBER
        INC  ALLOW ONE     * during BK amber, new requests should be queued
        LD1  TEN           * 5 s = 10 × ½ s
BKAMB   JSJ  HALF
        DEC1 1
        J1P  BKAMB

* ----- back to Del Mar green; cycle restarts
        LDX  X_DM_GREEN
        STZ  ET
        JMP  DMGREEN

* ========================= ½-second delay + request sampler =============

* HALF: Busy-wait for exactly 0.5 s (per HS calibration) and
*       if ALLOW=1 and overflow toggle is ON, set REQP←1.
HALF    STJ  RET
        LD2  HS
H1      DEC2 1
        J2P  H1
* Check overflow request switch
        LDA  ALLOW
        JZ   RETU
        JOV  SETR           * Jumps iff switch has been pressed; clears OV
        JMP  RETU
SETR    INC  REQP ONE
RETU    JMP  RET

        END  START</code></pre>
<p><strong>How it works</strong></p>
<ul>
<li>Default is Del Mar green + WALK, Berkeley red + DON’T WALK.</li>
<li>The loop labelled <code>DMLP</code> keeps Del Mar green and samples the overflow every ½ s. A request is armed only when Del Mar is green or amber, or when Berkeley is amber (i.e., whenever Berkeley is not green). This is managed by the <code>ALLOW</code> flag.</li>
<li>Once (i) a request is pending and (ii) Del Mar has been green for at least 30 s, we launch the 12-s pre-amber (8 s flash + 4 s steady DON’T WALK), then 8 s amber, then give Berkeley 20 s green (with its own flash/steady sequence), 5 s amber, and return to Del Mar green.</li>
<li>During Berkeley green we purposely ignore new presses; people cross on that cycle. During other phases we queue a press (by setting <code>REQP</code>), guaranteeing that the next Del Mar green will terminate at the earliest lawful moment (≥30 s with a full 12-s pre-amber).</li>
</ul>
<blockquote class="blockquote">
<p>Calibrate <code>HS</code> once for your MIX timing so that the loop under label <code>DELAY/H1</code> takes exactly half a second. After that, all required durations are exact by construction.</p>
</blockquote>
</section>
<section id="section-14" class="level3">
<h3 class="anchored" data-anchor-id="section-14">21 [28]</h3>
<p>Here’s a complete MIXAL program that builds the 23×23 magic square by the classical “Siamese” (Ibn al-Haytham) rule described in the problem, stores it in memory, and prints all 23 rows on the line printer.</p>
<ul>
<li>We index rows/columns 1..23.</li>
<li>Cell <span class="math inline">\((i,j)\)</span> lives at address <code>BASE + 23*(i-1) + j</code>.</li>
<li>Start with 1 just below the center: <span class="math inline">\((i,j)=(13,12)\)</span>.</li>
<li>Step down-right; when that destination is already filled, drop two rows (same column).</li>
<li>Printing puts each value as three right-aligned digits followed by a blank, 23 per line.</li>
</ul>
<pre class="mixal"><code>* TAOCP v1 §1.3.2 — Ex.21  Magic square (order 23) with Siamese method
* rI1 ≡ i (row 1..23), rI2 ≡ j (col 1..23), rI3 ≡ addr pointer, rI4 ≡ line word ptr

        ORIG 3000
PRN     EQU 18

* ---- character helpers -------------------------------------------------------
SPCW    ALF 00000          * one byte blank at (1:1)
Z0W     ALF 00000          * '0' at (1:1)
SPC     CON 0
D0      CON 0

* ---- constants ---------------------------------------------------------------
N       CON 23
BASE    CON 2000           * table base: uses 2000..2528 (529 cells)
LINE    EQU 2600           * 24-word printer line buffer (safe, out of the way)

ONE     CON 1
TWO     CON 2
TW3     CON 23
N2      CON 529            * N^2

* ---- work cells --------------------------------------------------------------
I       CON 0
J       CON 0
K       CON 0              * number to place
ADDR    CON 0
HUND    CON 0
TENS    CON 0
ONES    CON 0
RET     CON 0

* ====================== main ==================================================
START   LDA  SPCW(1:1);  STA SPC
        LDA  Z0W(1:1);   STA D0

* clear the 23×23 table to 0
        ENT1 1
CLRROW  ENT2 1
CLRJ    ENTA BASE
        ADD  I
        DEC  A 1
        MUL  N
        ADD  J
        STA  ADDR
        LD3  ADDR
        STZ  0,3
        INC2 1
        LDA  J
        CMPA N
        JL   CLRJ
        INC1 1
        LDA  I
        CMPA N
        JL   CLRROW

* initial position: just below the middle square (i=13, j=12)
        ENTA 13;  STA I
        ENTA 12;  STA J
        ENTA 1;   STA K

* ------------- fill loop: K from 1..N^2 --------------------------------------
PLACE   JSJ  ATIJ          * rI3 points to (i,j)
        LDA  K
        STA  0,3           * put K
        LDA  K
        CMPA N2
        JE   PRINTALL      * done filling

* compute tentative (i+1, j+1) with wrap
        LDA  I; ADD ONE; CMPA N; JLE IOK; SUB N
IOK     STA  HUND          * reuse HUND as temp (i') to save a cell
        LDA  J; ADD ONE; CMPA N; JLE JOK; SUB N
JOK     STA  TENS          * temp (j')

* empty? if yes, move there; else i ← i+2 mod N (j unchanged)
        ENTA BASE
        ADD  HUND
        DEC  A 1
        MUL  N
        ADD  TENS
        STA  ADDR
        LD3  ADDR
        LDA  0,3
        JZ   MOVEIJ
        LDA  I; ADD TWO; CMPA N; JLE IDONE; SUB N
IDONE   STA  I
        JMP  NEXTK
MOVEIJ  LDA  HUND; STA I
        LDA  TENS; STA J

NEXTK   LDA  K; ADD ONE; STA K
        JMP  PLACE

* ---------------- compute rI3=address for (I,J) -------------------------------
ATIJ    STJ  RET
        ENTA BASE
        ADD  I
        DEC  A 1
        MUL  N
        ADD  J
        STA  ADDR
        LD3  ADDR
        JMP  RET

* ======================= printing ============================================

PRINTALL
        ENT1 1
ROWLP   ENT2 1
        LD4  LINE

COLLP   * fetch value a(i,j)
        ENTA BASE
        ADD  I
        DEC  A 1
        MUL  N
        ADD  J
        STA  ADDR
        LD3  ADDR
        LDA  0,3

* extract 3 digits (hundreds, tens, ones) with two divisions
        ENTX 0
        DIV  =10=
        STX  ONES
        LDA  A
        ENTX 0
        DIV  =10=
        STX  TENS
        STA  HUND

* byte(1) ← hundreds or blank
        LDA  HUND
        JZ   HBL
        ADD  D0
        STA  0,4(1:1)
        JMP  TBYTE
HBL     LDA  SPC
        STA  0,4(1:1)

* byte(2) ← tens or blank (if hundreds and tens both 0)
TBYTE   LDA  HUND
        JNZ  TDIG
        LDA  TENS
        JZ   TBL
TDIG    LDA  TENS
        ADD  D0
        STA  0,4(2:2)
        JMP  OPUT
TBL     LDA  SPC
        STA  0,4(2:2)

* byte(3) ← ones (always a digit)
OPUT    LDA  ONES
        ADD  D0
        STA  0,4(3:3)

* byte(4) and (5) ← blanks (separator + tidy)
        LDA  SPC
        STA  0,4(4:4)
        STA  0,4(5:5)

        INC4 1
        INC2 1
        LDA  J
        CMPA N
        JL   COLLP

* print the 23-word line
        OUT  LINE(PRN)

        INC1 1
        LDA  I
        CMPA N
        JL   ROWLP

        HLT
        END  START</code></pre>
<p><strong>Notes</strong></p>
<ul>
<li>Addressing. <code>ATIJ</code> computes the address for the current <span class="math inline">\((i,j)\)</span> and sets <code>rI3</code> so we can <code>LDA/STA 0,3</code>.</li>
<li>Wrap-around. After <code>i+1</code> or <code>i+2</code> we compare to <code>N</code> and subtract <code>N</code> if needed (the plane-tiling rule).</li>
<li>Printing.** Each of the 23 output words on a line holds <code>ddd</code> (three digits right-aligned plus a blank separator; byte 5 blank too). That’s simple and fits the printer’s 24-word line.</li>
<li>Memory used: table <code>2000..2528</code> (529 words) and line buffer <code>2600..2623</code>.</li>
</ul>
<p>Run this and you’ll get the <span class="math inline">\(23\times23\)</span> magic square, each row nicely formatted on the printer.</p>
</section>
<section id="section-15" class="level3">
<h3 class="anchored" data-anchor-id="section-15">22 [31]</h3>
<p>Here’s a fast MIXAL solution of the Josephus problem that prints the order-of-execution for <span class="math inline">\(n=24\)</span>, <span class="math inline">\(m=11\)</span>. It keeps a circular doubly-linked list in two arrays <code>NEXT[i]</code> and <code>PREV[i]</code> so that each kill is <span class="math inline">\(O(m)\)</span> pointer hops, and removal is <span class="math inline">\(O(1)\)</span>. It finally prints, for each man <span class="math inline">\(i=1,\dots,24\)</span>, the number <span class="math inline">\(1..24\)</span> telling when he is executed (the format is two digits per man, zero-padded).</p>
<pre><code>* EX 1.3.2 — Exercise 22 (Josephus): n = 24, m = 11
* Output: for i=1..24, the execution order of man i.

        ORIG 3000
PRN     EQU   18
N       EQU   24
M       EQU   11

LINE    EQU   3900                * 24-word printer line

* ------- helpers for printing -----------------------------------------------
Z0W     ALF  00000
SPCW    ALF  00000
D0      CON  0                    * '0' byte  (from Z0W(1:1))
SPC     CON  0                    * blank     (from SPCW(1:1))

* ------- tables (24 words each) ---------------------------------------------
NEXT    EQU   3600                * NEXT[i] : next alive after i
PREV    EQU   3624                * PREV[i] : previous alive before i
ORD     EQU   3648                * ORD[i]  : kill order of i (1..24)

* ------- scratch -------------------------------------------------------------
CUR     CON   0                   * current position in the circle
T       CON   0                   * current kill number (1..N)
TMP     CON   0
TEN     CON   10

RET     CON   0
ONES    CON   0
TENS    CON   0

* =========================  MAIN  ============================================

START   LDA  Z0W(1:1);  STA D0
        LDA  SPCW(1:1); STA SPC

* ---- build the circular doubly linked list for 1..N
        ENT1  1
INITLP  ENTA  0,1                 * A ← i
        ADD   =1=
        CMPA  =N+1=               * wrap next
        JL    OKN
        ENTA  1
OKN     STA   NEXT,1              * NEXT[i] ← (i%N)+1

        ENTA  0,1
        SUB   =1=
        JG    OKP
        ENTA  =N=
OKP     STA   PREV,1              * PREV[i] ← ((i-2+N)%N)+1

        INC1  1
        CMP1  =N+1=
        JL    INITLP

* ---- Josephus loop
        ENT1  1                   * CUR ← 1
        STA   CUR
        ENTA  1;  STA  T          * T ← 1  (first kill)

KILL    * advance m-1 steps: CUR ← NEXT^(m-1)(CUR)
        ENT2  M
        DEC2  1                   * rI2 ← m-1
ADVLP   LD3   CUR
        LDA   NEXT,3
        STA   CUR
        DEC2  1
        J2P   ADVLP

* mark execution order
        LD3   CUR
        LDA   T
        STA   ORD,3

* splice CUR out: NEXT[PREV[CUR]] ← NEXT[CUR];  PREV[NEXT[CUR]] ← PREV[CUR]
        LDA   PREV,3
        STA   TMP                 * TMP ← prev
        LDA   NEXT,3
        STA   CUR                 * CUR ← next (the one after the dead guy)

        LD4   TMP                 * write NEXT[prev] ← next
        STA   NEXT,4

        LD3   CUR                 * write PREV[next] ← prev
        LDA   TMP
        STA   PREV,3

* stop after N kills
        LDA   T
        CMPA  =N=
        JE    PRINT

        ADD   =1=
        STA   T
        JMP   KILL

* ============================ PRINT ==========================================

PRINT   LD4   LINE                * build a 24-word line
        ENT1  1
ROW     LD3   ORD,1               * value = ORD[i]
        LDA   0,3
        ENTX  0
        DIV   TEN
        STX   ONES
        STA   TENS

        LDA   TENS;  ADD D0;      STA 0,4(1:1)   * tens
        LDA   ONES;  ADD D0;      STA 0,4(2:2)   * ones
        LDA   SPC;                STA 0,4(3:3)   * space
        STA   0,4(4:4);           STA 0,4(5:5)   * padding blanks

        INC4  1
        INC1  1
        CMP1  =N+1=
        JL    ROW

        OUT   LINE(PRN)
        HLT

        END  START</code></pre>
<p><strong>What it prints (two digits per man, in order 1..24)</strong></p>
<p>For <span class="math inline">\(n=24\)</span>, <span class="math inline">\(m=11\)</span> the order-of-execution is</p>
<pre><code>15 12 22 08 16 11 23 21 03 05 01 17 10 07 24 19 20 18 09 14 04 02 13 06</code></pre>
<p>meaning: man 1 is 15th to die, man 2 is 12th, …, man 24 is 6th.</p>
</section>
<section id="section-16" class="level3">
<h3 class="anchored" data-anchor-id="section-16">23 [37]</h3>
<p>Below is a complete MIXAL program that reads a <span class="math inline">\(23\times 23\)</span> matrix of zeros and ones (one row per card on device 16, with columns 1–23 containing the digits ‘0’/‘1’), converts it to a crossword diagram, removing edge-connected black areas, numbering the white squares that start an Across or Down word, and prints the final picture on the line printer (device 18) exactly as specified: each puzzle cell is rendered by 5 columns × 3 rows of printer characters.</p>
<p>I have kept the code heavily annotated and very close to the text of the exercise, so you can change it easily (e.g., to other sizes).</p>
<p>What the program prints</p>
<ul>
<li><strong>White (unnumbered)</strong> cell → top row <code>"    +"</code>, middle row <code>"    +"</code>, bottom <code>"+++++"</code>.</li>
<li><strong>White (numbered)</strong> cell, number <code>nn</code> (2 digits, leading zero) → top <code>" nn +"</code>, middle <code>"    +"</code>, bottom <code>"+++++"</code>.</li>
<li><strong>Black</strong> cell → all three rows <code>"+++++"</code>.</li>
<li><strong>Outside</strong> cells (that became <code>−1</code> after the edge sweep): If the cell to the right is also <code>−1</code>, the right border is suppressed (<code>"     "</code> on the two upper rows); if the cell below** is <code>−1</code>, the bottom border is suppressed (<code>"     "</code> on the bottom row). This produces a clean rectangular outside frame like Fig. 19.</li>
</ul>
<pre class="mixal"><code>* TAOCP v1 §1.3.2 — Ex.23  Crossword diagram from a 23x23 0/1 matrix
* Input : 23 cards on device 16, cols 1..23 are digits 0/1 (one row per card)
* Output: puzzle drawn on device 18 (line printer), as in Fig. 19
* Method : Add a -1 border, flood -1 into edge-connected 1's, number starts,
*          then render 3 printer lines per puzzle row, 5 bytes per cell.

        ORIG 3000
PRN     EQU   18
CARD    EQU   16

* --------------- character codes we need (portable via ALF) ------------------
SPCW    ALF  00000           * blank in (1:1)
PLUSW   ALF  +0000           * '+' in (1:1)
Z0W     ALF  00000           * '0' in (1:1)

SPC     CON  0
PLUS    CON  0
D0      CON  0

* --------------- general constants and pointers ------------------------------
N       CON   23
NP1     CON   24
N2      CON   529
FIVE    CON   5
THREE   CON   3
ONE     CON   1
TWO     CON   2
ZERO    CON   0
NEG1    CON   -1
TEN     CON   10

* --------------- storage layout ---------------------------------------------
* use a 25x25 board B(i,j), 0..24 in both directions
* (board base at B), and a NUM(i,j) table for numbers (1..K)
B       EQU   5000                    * 25*25 = 625 words used
NUM     EQU   B+625
LINE    EQU   NUM+625                 * 24-word print line buffer
CARDW   EQU   LINE+24                 * 24-word card buffer

* --------------- scratch -----------------------------------------------------
I       CON 0
J       CON 0
K       CON 0
CHG     CON 0
ADDR    CON 0
T       CON 0
Q       CON 0
R       CON 0
RET     CON 0
D1      CON 0
D10     CON 0

* ====================== main ==================================================
START   LDA  SPCW(1:1);  STA SPC
        LDA  PLUSW(1:1); STA PLUS
        LDA  Z0W(1:1);   STA D0

* ---------- zero NUM and fill B with -1 border, 0 inside ---------------------
        ENT1 0
BORDR   ENT2 0
        ENTA  B
        ADD   I
        MUL   =25=
        ADD   J
        STA   ADDR
        LD3   ADDR
* set B(i,j):
        LDA   I
        JE    SETM1
        CMPA  NP1
        JE    SETM1
        LDA   J
        JE    SETM1
        CMPA  NP1
        JE    SETM1
        STZ   0,3                     * interior initial 0
        JMP   NEXTB
SETM1   LDA   NEG1
        STA   0,3
NEXTB   * NUM(i,j) ← 0
        LDA   ZERO
        STA   NUM- B,3                * same index, other table

        INC2  1
        LDA   J
        CMPA  =25=
        JL    BORDR
        INC1  1
        LDA   I
        CMPA  =25=
        JL    BORDR

* ------------------ read 23 cards; store 0/1 into B(1..23,1..23) -------------
        ENT1 1                         * row i = 1..23
RDROW   IN   CARDW(CARD)
        JBUS *      (CARD)             * wait for card
        ENT2 1
        LD4  CARDW
RDCOL   LDA  0,4(0:0)                  * next card byte
        ADD  =0=                       * put in A with sign '+'
        SUB  D0
        JZ   ISZERO
        ENTA 1
        JMP  STORE
ISZERO  ENTA 0
STORE   STX  R                         * (X changed by ADD/SUB? guard)
        ENTA  B
        ADD   I
        MUL   =25=
        ADD   J
        STA   ADDR
        LD3   ADDR
        LDA   ZERO
        ADD   A                        * A already 0 or 1
        STA   0,3

        INC4  1
        INC2  1
        LDA   J
        CMPA  N
        JL    RDCOL

        INC1  1
        LDA   I
        CMPA  N
        JLE   RDROW

* ------------------ flood -1 from border into all edge-connected 1's ---------
FLOOP   STZ  CHG
        ENT1 1
FI      ENT2 1
FJ      * process only original interior domain 1..23
        ENTA  B
        ADD   I
        MUL   =25=
        ADD   J
        STA   ADDR
        LD3   ADDR
        LDA   0,3
        CMPA  =1=
        JNE   NEXTJ

        * if a 1 is adjacent (4-neigh) to -1, turn it into -1
        ENTA  B
        ADD   I
        DEC   A ONE
        MUL   =25=
        ADD   J
        STA   T
        LDA   0,T
        CMPA  NEG1
        JE    MAKE
        ENTA  B
        ADD   I
        INC   A ONE
        MUL   =25=
        ADD   J
        STA   T
        LDA   0,T
        CMPA  NEG1
        JE    MAKE
        ENTA  B
        ADD   I
        MUL   =25=
        ADD   J
        DEC   A ONE
        STA   T
        LDA   0,T
        CMPA  NEG1
        JE    MAKE
        ENTA  B
        ADD   I
        MUL   =25=
        ADD   J
        INC   A ONE
        STA   T
        LDA   0,T
        CMPA  NEG1
        JNE   NEXTJ
MAKE    LDA   NEG1
        STA   0,3
        ENTA  1
        STA   CHG
NEXTJ   INC2  1
        LDA   J
        CMPA  N
        JLE   FJ
        INC1  1
        LDA   I
        CMPA  N
        JLE   FI
        LDA   CHG
        JNZ   FLOOP

* ------------------ numbering: starts of across / down -----------------------
        STZ   K
        ENT1  1
NI      ENT2  1
NJ      ENTA  B
        ADD   I
        MUL   =25=
        ADD   J
        STA   ADDR
        LD3   ADDR
        LDA   0,3
        JZ    WHITEOK
        JMP   NXTJ
WHITEOK * check down start: (i==1 or B(i-1,j)!=0) and (i&lt;23 and B(i+1,j)==0)
        ENTA  0
        STA   T
        LDA   I
        JNE   CI1
        ENTA  1
        STA   T
        JMP   C2
CI1     ENTA  B
        ADD   I
        DEC   A ONE
        MUL   =25=
        ADD   J
        LDA   0,A
        JNZ   C2
        ENTA  0
        STA   T
C2      LDA   T
        JZ    NOTD
        LDA   I
        CMPA  N
        JE    NOTD
        ENTA  B
        ADD   I
        INC   A ONE
        MUL   =25=
        ADD   J
        LDA   0,A
        JNZ   NOTD
        ENTA  1
        STA   T                 * down start
NOTD    * check across start
        LDA   T
        JNZ   NUMBER
        LDA   J
        JNE   CJ1
        ENTA  1
        STA   T
        JMP   C4
CJ1     ENTA  B
        ADD   I
        MUL   =25=
        ADD   J
        DEC   A ONE
        LDA   0,A
        JNZ   C4
        ENTA  0
        STA   T
C4      LDA   T
        JNZ   NUMBERC
        LDA   J
        CMPA  N
        JE    NXTJ
        ENTA  B
        ADD   I
        MUL   =25=
        ADD   J
        INC   A ONE
        LDA   0,A
        JNZ   NXTJ
NUMBERC ENTA  1
        STA   T
NUMBER  LDA   K
        ADD   ONE
        STA   K
        STA   NUM- B,3
NXTJ    INC2  1
        LDA   J
        CMPA  N
        JLE   NJ
        INC1  1
        LDA   I
        CMPA  N
        JLE   NI

* ------------------ render to printer ----------------------------------------
        ENT1  1
ROW     * we emit 3 printer lines for row i
        LD3   =1=
        STA   T                * t = which subrow (1..3)

SUBROW  LD4   LINE
        ENT2  1
COL     ENTA  B
        ADD   I
        MUL   =25=
        ADD   J
        STA   ADDR
        LD3   ADDR
        LDA   0,3              * val = B(i,j)
        JN    OUTM1            * negative → outside
        JZ    OUTWHT           * zero → white
        JMP   OUTBLK           * positive → black

* ----- black square: '+++++' on all 3 subrows
OUTBLK  LDA   PLUS
        STA   0,4(1:1)
        STA   0,4(2:2)
        STA   0,4(3:3)
        STA   0,4(4:4)
        STA   0,4(5:5)
        JMP   NEXTC

* ----- white square
OUTWHT  LDA   T
        CMPA  =1=
        JNE   W2
        * top row: maybe a number
        LDA   NUM- B,3
        JZ    WTOPS
        ENTX  0
        DIV   TEN
        STX   D1
        STA   D10
        LDA   SPC;  STA 0,4(1:1)
        LDA   D10; ADD D0; STA 0,4(2:2)
        LDA   D1;  ADD D0; STA 0,4(3:3)
        LDA   SPC; STA 0,4(4:4)
        LDA   PLUS;STA 0,4(5:5)
        JMP   NEXTC
WTOPS   LDA   SPC; STA 0,4(1:1); STA 0,4(2:2); STA 0,4(3:3); STA 0,4(4:4)
        LDA   PLUS; STA 0,4(5:5)
        JMP   NEXTC
W2      LDA   T
        CMPA  =2=
        JNE   W3
        * middle row: "    +"
        LDA   SPC; STA 0,4(1:1); STA 0,4(2:2); STA 0,4(3:3); STA 0,4(4:4)
        LDA   PLUS; STA 0,4(5:5)
        JMP   NEXTC
W3      * bottom row: "+++++"
        LDA   PLUS
        STA   0,4(1:1); STA 0,4(2:2); STA 0,4(3:3); STA 0,4(4:4); STA 0,4(5:5)
        JMP   NEXTC

* ----- outside (-1) square: suppress borders that abut -1 at right/below
OUTM1   LDA   T
        CMPA  =3=
        JE    M1BOT
        * top/mid subrows
        * if right neighbor is -1 → five blanks; else "    +"
        ENTA  B
        ADD   I
        MUL   =25=
        ADD   J
        INC   A ONE
        LDA   0,A
        CMPA  NEG1
        JE    ALLSP
        LDA   SPC; STA 0,4(1:1); STA 0,4(2:2); STA 0,4(3:3); STA 0,4(4:4)
        LDA   PLUS; STA 0,4(5:5)
        JMP   NEXTC
ALLSP   LDA   SPC
        STA   0,4(1:1); STA 0,4(2:2); STA 0,4(3:3); STA 0,4(4:4); STA 0,4(5:5)
        JMP   NEXTC
M1BOT   * bottom subrow
        ENTA  B
        ADD   I
        INC   A ONE
        MUL   =25=
        ADD   J
        LDA   0,A
        CMPA  NEG1
        JE    ALLSP
        LDA   PLUS
        STA   0,4(1:1); STA 0,4(2:2); STA 0,4(3:3); STA 0,4(4:4); STA 0,4(5:5)

NEXTC   INC4 1
        INC2 1
        LDA  J
        CMPA N
        JLE  COL

        OUT  LINE(PRN)

        LDA  T
        ADD  ONE
        STA  T
        CMPA THREE
        JLE  SUBROW

        INC1 1
        LDA  I
        CMPA N
        JLE  ROW

        HLT
        END  START</code></pre>
<p><strong>Notes, hints, and adjustments</strong></p>
<ul>
<li><strong>Card input</strong>: the code expects 23 cards; each of the first 23 bytes is <code>'0'</code> or <code>'1'</code>. If your MIX monitor uses a different input device, just change <code>CARD=16</code> and the <code>IN</code>/<code>JBUS</code> calls accordingly.</li>
<li><strong>Edge removal</strong> (the “−1 flood”): we iterate until a full pass makes no change; for a 23×23 matrix this is trivial in time.</li>
<li><strong>Numbering rule</strong>: a white square gets a number if it begins a <strong>down</strong> word (white below, not white above) or an <strong>across</strong> word (white right, not white left). Numbers are two digits with a <strong>leading zero</strong> as in the book’s figure.</li>
<li><strong>Exact line lengths</strong>: each printer line has 23 boxes × 5 bytes = 115 bytes; the line buffer has 24 words (120 bytes), so the last five are blank and harmless.</li>
<li>You can change <code>B</code>, <code>NUM</code>, or <code>LINE</code> bases if they clash with your monitor; all addresses are absolute here to keep the program self-contained.</li>
</ul>
<p>This produces a printout that matches the layout in Fig. 19: a plus-bordered diagram, numbers placed at the correct starts, black squares filled with ‘+’, and edge-connected black regions removed.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../vol-1/1.3.1.html" class="pagination-link" aria-label="1.3.1 Description of MIX">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">1.3.1 Description of MIX</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../vol-1/1.3.3.html" class="pagination-link" aria-label="1.3.3 Applications to Permutation">
        <span class="nav-page-text"><span class="chapter-title">1.3.3 Applications to Permutation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>